### ISSUE TITLE
bug！

### ISSUE THREAD

**Issue by brizer** [xiaocheng555/el-table-virtual-scroll#1]
这个封装的很好，但是有一些bug，你可以按照element-ui官方表格的demo都跑一下，我目前发现不少都是跑不通的，基本都是高度的设置导师了样式问题。

**Comment by xiaocheng555** [comment]
> 这个封装的很好，但是有一些bug，你可以按照element-ui官方表格的demo都跑一下，我目前发现不少都是跑不通的，基本都是高度的设置导师了样式问题。

好提议，我尽量完善一下组件

**Comment by brizer** [comment]
> > 这个封装的很好，但是有一些bug，你可以按照element-ui官方表格的demo都跑一下，我目前发现不少都是跑不通的，基本都是高度的设置导师了样式问题。
> 
> 好提议，我尽量完善一下组件

试了下，在正确传递keyProp的情况下，都是可以正常的。非常给力啊，又不需要侵入式。

**Comment by xiaocheng555** [comment]
ok，我顺便更新了demo，涉及element-ui表格的多个场景
![image](https://user-images.githubusercontent.com/19643785/200108208-9098804e-03f0-480a-a77b-1400d03a02b2.png)

**Comment by xiaocheng555** [comment]
> > > 这个封装的很好，但是有一些bug，你可以按照element-ui官方表格的demo都跑一下，我目前发现不少都是跑不通的，基本都是高度的设置导师了样式问题。
> > 
> > 
> > 好提议，我尽量完善一下组件
> 
> 试了下，在正确传递keyProp的情况下，都是可以正常的。非常给力啊，又不需要侵入式。

ok，我顺便更新了demo，涉及element-ui表格的多个场景
![image](https://user-images.githubusercontent.com/19643785/200108347-81858991-7672-4cb6-be03-5940723eb206.png)
