### ISSUE TITLE
对element-plus的table的支持

### ISSUE THREAD

**Issue by brizer** [xiaocheng555/el-table-virtual-scroll#10]
建议加上对element-plus中table的支持

**Comment by xiaocheng555** [comment]
> 建议加上对element-plus中table的支持

element-plus 有虚拟化表格组件了，用那个就行了
<img width="889" alt="image" src="https://user-images.githubusercontent.com/19643785/217163368-3d70bc34-7fee-4728-99c0-cbe888220a4b.png">

**Comment by brizer** [comment]
> > 建议加上对element-plus中table的支持
> 
> element-plus 有虚拟化表格组件了，用那个就行了 <img alt="image" width="889" src="https://user-images.githubusercontent.com/19643785/217163368-3d70bc34-7fee-4728-99c0-cbe888220a4b.png">

如果你仔细看了他的用法后你会发现和table的api是完全不兼容的，历史包袱太重了，我现在正在升级基于你的element无限表格到element-plus的表格。目前需要改动的就是一个$set，如果你有空自己也可以试试。

**Comment by xiaocheng555** [comment]
> > > 建议加上对element-plus中table的支持
> > 
> > 
> > element-plus 有虚拟化表格组件了，用那个就行了 <img alt="image" width="889" src="https://user-images.githubusercontent.com/19643785/217163368-3d70bc34-7fee-4728-99c0-cbe888220a4b.png">
> 
> 如果你仔细看了他的用法后你会发现和table的api是完全不兼容的，历史包袱太重了，我现在正在升级基于你的element无限表格到element-plus的表格。目前需要改动的就是一个$set，如果你有空自己也可以试试。

了解，我看看如何兼容

**Comment by brizer** [comment]
https://v3-migration.vuejs.org/zh/breaking-changes/watch.html#frontmatter-title   对data的兼容，需要增加deep，来兼容vue3

**Comment by xiaocheng555** [comment]
> 建议加上对element-plus中table的支持

vue3版本在这：
https://github.com/xiaocheng555/el-table-virtual-scroll-next
