### ISSUE TITLE
多选select-change事件在表格数据更新后未触发，导致旧数据未清除

### ISSUE THREAD

**Issue by cug-zgj** [xiaocheng555/el-table-virtual-scroll#100]
我实现了一个批量删除的操作，多选选中后，在select-change事件中，绑定了selectedArr。点击批量删除，将selectedArr对应的数据删掉，然后重查更新table。但是重查后，select-change并未再次触发，导致selectedArr中的旧数据仍然存在。我看了element-ui原生的table，多选更新数据后，会再次触发select-change，更新数据。

**Comment by xiaocheng555** [comment]
> 我实现了一个批量删除的操作，多选选中后，在select-change事件中，绑定了selectedArr。点击批量删除，将selectedArr对应的数据删掉，然后重查更新table。但是重查后，select-change并未再次触发，导致selectedArr中的旧数据仍然存在。我看了element-ui原生的table，多选更新数据后，会再次触发select-change，更新数据。

2.0.1 版本已经修复
