### ISSUE TITLE
el-table-column使用min-width+show-overflow-tooltip属性时拖动表头修改列宽度单元格宽度未刷新

### ISSUE THREAD

**Issue by jsonho** [xiaocheng555/el-table-virtual-scroll#102]
<el-table-column
                        prop='lease_unit_code'
                        :label='$t("leaseship.unitName")'
                        min-width='120px'
                        show-overflow-tooltip/>

<img width="188" alt="image" src="https://github.com/user-attachments/assets/2d5889f2-95b5-4efc-a902-7a0e7789092e">

**Comment by jsonho** [comment]
<el-table-column
                        prop='lease_unit_code'
                        :label='$t("leaseship.unitName")'
                        min-width='120px'
                        show-overflow-tooltip
                    />

**Comment by jsonho** [comment]
`<el-table-column
                        prop='lease_unit_code'
                        :label='$t("leaseship.unitName")'
                        min-width='120px'
                        show-overflow-tooltip
                    />`

**Comment by xiaocheng555** [comment]
> `<el-table-column prop='lease_unit_code' :label='$t("leaseship.unitName")' min-width='120px' show-overflow-tooltip />`

没有复现出来，有完整的demo吗

**Comment by izhl2020** [comment]
![image](https://github.com/user-attachments/assets/8a2baf7e-3a81-4e65-9779-452335508a43)
![image](https://github.com/user-attachments/assets/1d0e2689-c1c4-4d65-b10a-9051f42e54ef)
![image](https://github.com/user-attachments/assets/006cd317-f5a0-4fa7-9909-bb2f22b1dbce)


我出现了同样的问题，我第一次拖拽的时没有隐藏掉，第二次拖拽日期列后，‘桃花坞里桃花庵，桃花庵里桃花仙...’就出现隐藏状态了
![65d58d785568dc4707b2e00e6a39a15](https://github.com/user-attachments/assets/f5bd6edd-df9d-4e1c-9d0f-0a4daaa6e99f)

**Comment by xiaocheng555** [comment]
> 我出现了同样的问题，我第一次拖拽的时没有隐藏掉，第二次拖拽日期列后，‘桃花坞里桃花庵，桃花庵里桃花仙...’就出现隐藏状态了

好的

**Comment by xiaocheng555** [comment]
> ![image](https://private-user-images.githubusercontent.com/39878254/396799257-8a2baf7e-3a81-4e65-9779-452335508a43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDY4NTcsIm5iZiI6MTczNDUwNjU1NywicGF0aCI6Ii8zOTg3ODI1NC8zOTY3OTkyNTctOGEyYmFmN2UtM2E4MS00ZTY1LTk3NzktNDUyMzM1NTA4YTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA3MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDI4NmIzZTJiMzk4OWRjMWI0YmMwZTI2NTAxMTU0MjdhNDg4ZGI5ZjlhMmU4YmY1Mjk2MjNmYzEwNzVkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5otoZf-kR06bJeJ2WWIwtwW-sx4IidnmdO7HfkXzaoY) ![image](https://private-user-images.githubusercontent.com/39878254/396799325-1d0e2689-c1c4-4d65-b10a-9051f42e54ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDY4NTcsIm5iZiI6MTczNDUwNjU1NywicGF0aCI6Ii8zOTg3ODI1NC8zOTY3OTkzMjUtMWQwZTI2ODktYzFjNC00ZDY1LWIxMGEtOTA1MWY0MmU1NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA3MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOTlkODQ2NmJlMmIyOTVhZjdhZjcwMGFiZGIxNWY5YWVlNjE4OTJkYTM5YjE1YTZjNWNkMWFlZDNhM2I5ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BpxK0DbdgCEDUhGu7wC1jDME8n68pVM4l3hLhoUiKnk) ![image](https://private-user-images.githubusercontent.com/39878254/396799468-006cd317-f5a0-4fa7-9909-bb2f22b1dbce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDY4NTcsIm5iZiI6MTczNDUwNjU1NywicGF0aCI6Ii8zOTg3ODI1NC8zOTY3OTk0NjgtMDA2Y2QzMTctZjVhMC00ZmE3LTk5MDktYmIyZjIyYjFkYmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA3MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNjZmMGIyZDE3MThmMzlhODNkMjA0OGVkMTkxZjhkMTM4Y2IyZmI1ODQ3N2RiM2IxODZiNWQ0ODcwYmI1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NwOW5W0nDqU2xFGlatfetPkFwcia8OQaLm-0GfCoGk4)
> 
> 我出现了同样的问题，我第一次拖拽的时没有隐藏掉，第二次拖拽日期列后，‘桃花坞里桃花庵，桃花庵里桃花仙...’就出现隐藏状态了 ![65d58d785568dc4707b2e00e6a39a15](https://private-user-images.githubusercontent.com/39878254/396799952-f5bd6edd-df9d-4e1c-9d0f-0a4daaa6e99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDY4NTcsIm5iZiI6MTczNDUwNjU1NywicGF0aCI6Ii8zOTg3ODI1NC8zOTY3OTk5NTItZjViZDZlZGQtZGY5ZC00ZTFjLTlkMGYtMGE0ZGFhYTZlOTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA3MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZmU4MDY2ZGFlZDVjNTk4MDEyMTZlN2M5YTljOWIzMWI2ZTQ0Zjk2MTRlMTAwYjY3YWNkNDBmOGU3NmUzZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9QNS95QWr1J7g5WeODH3vs0lYVC62Vfo8yM_GpS1EMU)

版本2.0.2 已修复
