### ISSUE TITLE
el-table使用动态高度时出现bug

### ISSUE THREAD

**Issue by zhaosong123843** [xiaocheng555/el-table-virtual-scroll#105]
el-table里面的表格高度不能设置成动态的吗？我尝试使用:height来适应高度变化，但是出现bug
![企业微信截图_17326758956633](https://github.com/user-attachments/assets/8c92037b-dbd3-4dcb-9b39-7f7decbfb71e)
这个是设置成动态高度的时候就变成这样了，当我点击网页的检查时，表格就显示出来了，就像下方的图，
![企业微信截图_1732676013196](https://github.com/user-attachments/assets/77416371-8628-4efb-96e9-ac4c014e76ca)
请问这是怎么回事？
`
<VirtualScroll :data="filterTable" :item-size="50" key-prop="id" @change="(renderData) => virtualList = renderData">
      <el-table :data="virtualList" border :height="tableHeight"  style="width: 100%;margin-top: 10px;"
        :header-cell-style="{ background: '#f4f3f9', color: '#606266', 'line-height': '1%', borderColor: 'black', 'font-size': 'larger' }"
        :cell-style="{ 'text-align': 'left', 'font-size': 'small' }" size="mini" ref="filterTable"
        @selection-change="handleSelectionChange" row-key="id">
        <el-table-column type="index" label="序号" :index="indexMethod" width="80">
        </el-table-column>
        <el-table-column v-for="(val, index) in tableStyle.prop" :prop="tableStyle.prop[index]"
          :label="tableStyle.label[index]" :key="index"></el-table-column>
        <el-table-column label="操作" width="100">
          <template slot-scope="scope">
            <el-button type="text" size="small" @click="editClick(scope.row)">编辑</el-button>
            <el-divider direction="vertical"></el-divider>
            <el-button type="text" size="small" slot="reference" @click="deletSingleInfo(scope.row)">删除</el-button>
          </template>
        </el-table-column>
        <el-table-column type="selection" width="55">
        </el-table-column>
      </el-table>
    </VirtualScroll>
`

**Comment by xiaocheng555** [comment]
高度变化的时候，执行一下update方法
