### ISSUE TITLE
如果下面的表格是树结构的化会有bug

### ISSUE THREAD

**Issue by caihai123** [xiaocheng555/el-table-virtual-scroll#11]
如果下面的表格是树结构的化会有bug

**Comment by xiaocheng555** [comment]
> 如果下面的表格是树结构的化会有bug

具体是什么bug，有没有图或者代码；是表格嵌套的情况吗

**Comment by caihai123** [comment]
![image](https://user-images.githubusercontent.com/47770861/222024812-01585eac-2ab3-4e22-88b6-57b2017a39b4.png)
我没有使用VirtualColumn，代码是这样的，因为数据种含有children并且设置了row-key，所以被视为树形数据，但是在滚动到有下级的时候会出现明显的卡顿，并可能会出现滚动条消失，大片白屏的现象，就想下面的图一样
![image](https://user-images.githubusercontent.com/47770861/222025408-1cb78c6e-76d1-4636-a6f3-07ed64a1751b.png)

**Comment by xiaocheng555** [comment]
> 

我这里复现不出来，或者你能不能提供一个复现的demo代码，可以加QQ：1052745517 方便交流一下

**Comment by xiaocheng555** [comment]
> ![image](https://user-images.githubusercontent.com/47770861/222024812-01585eac-2ab3-4e22-88b6-57b2017a39b4.png) 我没有使用VirtualColumn，代码是这样的，因为数据种含有children并且设置了row-key，所以被视为树形数据，但是在滚动到有下级的时候会出现明显的卡顿，并可能会出现滚动条消失，大片白屏的现象，就想下面的图一样 ![image](https://user-images.githubusercontent.com/47770861/222025408-1cb78c6e-76d1-4636-a6f3-07ed64a1751b.png)

我这里复现不出来，或者你能不能提供一个复现的demo代码，可以加QQ：1052745517 方便交流一下
