### ISSUE TITLE
怎样打包成js引入

### ISSUE THREAD

**Issue by gaoningguo** [xiaocheng555/el-table-virtual-scroll#12]
怎样打包成这样子引入，本人后端对这个不太熟
![image](https://user-images.githubusercontent.com/112529571/222329458-a4dae5b9-0f2b-49e1-85f9-61666dc26d69.png)

**Comment by xiaocheng555** [comment]
引入：
```
<script src="./el-table-virtual-scroll.min.js"></script>
```
js文件可以从 https://github.com/xiaocheng555/el-table-virtual-scroll/blob/master/dist/el-table-virtual-scroll.min.js 这里拿，也可以使用npm下载某个版本包放在项目中，引入dist/el-table-virtual-scroll.min.js 文件。【版本1.0.11 以上】

使用：
```
const { VirtualScroll, VirtualColumn } = window.ElTableVirtualScroll

export default {
  components: {
    VirtualScroll,
    VirtualColumn
  }
}
```
