### ISSUE TITLE
使用固定表格功能时，固定位置的滚动条无法拖动.

### ISSUE THREAD

**Issue by AlbertYu8467** [xiaocheng555/el-table-virtual-scroll#14]
不知可否将此行代码 
 el.wrapEl.style.height = wrapHeight + 'px'
 改为如下：
if(className.includes('fixed')){
   let scrollBarHeight = 10
   el.wrapEl.style.height = wrapHeight - scrollBarHeight   + 'px'
}

**Comment by xiaocheng555** [comment]
[滚动条](https://xiaocheng555.github.io/el-table-virtual-scroll/#/BasicDemo?code=BasicDemo&codeTitle=%E5%9F%BA%E7%A1%80%E8%A1%A8%E6%A0%BC)

这个demo滚动条可以拖动的。你指的无法拖动是怎么样的，竖向滚动条无法拖动吗，为什么加上scrollBarHeight 高度就可以拖动了

**Comment by xiaocheng555** [comment]
> 不知可否将此行代码 el.wrapEl.style.height = wrapHeight + 'px' 改为如下： if(className.includes('fixed')){ let scrollBarHeight = 10 el.wrapEl.style.height = wrapHeight - scrollBarHeight + 'px' }

[滚动条](https://xiaocheng555.github.io/el-table-virtual-scroll/#/BasicDemo?code=BasicDemo&codeTitle=%E5%9F%BA%E7%A1%80%E8%A1%A8%E6%A0%BC)

这个demo滚动条可以拖动的。你指的无法拖动是怎么样的，竖向滚动条无法拖动吗，为什么加上scrollBarHeight 高度就可以拖动了
