### ISSUE TITLE
使用virtual-scroll包裹el-table无法准确合并单元格，合并单元格会异常

### ISSUE THREAD

**Issue by zhanghaifei1997** [xiaocheng555/el-table-virtual-scroll#15]
![image](https://user-images.githubusercontent.com/57278786/230772185-466a2eea-9f98-4053-8750-46c2931a36ff.png)

**Comment by xiaocheng555** [comment]
> ![image](https://user-images.githubusercontent.com/57278786/230772185-466a2eea-9f98-4053-8750-46c2931a36ff.png)

好的，我看看

**Comment by xiaocheng555** [comment]
> ![image](https://user-images.githubusercontent.com/57278786/230772185-466a2eea-9f98-4053-8750-46c2931a36ff.png)

最近有点忙，修复bug晚了点，抱歉。

**bug产生原因**：由于表格使用了虚拟滚动，只会渲染可见范围内的数据，滚动时会将合并行给割裂开来，使得部分行显示，部分不显示，导致显示错误。

**解决方法** ：对于行合并，增加rowSpanKey 属性去兼容，rowSpanKey函数需要返回每组合并行中共用的key值，组件内部会根据key值进行计算并完整显示合并行内容。如你给出的图中，key则为楼层对应的属性值，rowSpanKey(row) { return row[楼层] }。
版本升级到1.0.13

<img width="950" alt="image" src="https://user-images.githubusercontent.com/19643785/231434476-ce044f8b-acb6-4520-bc10-574b1b69e6fb.png">



详细请看demo和源码：
https://xiaocheng555.github.io/el-table-virtual-scroll/#/Rowspan?code=Rowspan&codeTitle=%E5%90%88%E5%B9%B6%E8%A1%8C

**Comment by xiaocheng555** [comment]
> > ![image](https://user-images.githubusercontent.com/57278786/230772185-466a2eea-9f98-4053-8750-46c2931a36ff.png)
> 
> 最近有点忙，修复bug晚了点，抱歉。
> 
> **bug产生原因**：由于表格使用了虚拟滚动，只会渲染可见范围内的数据，滚动时会将合并行给割裂开来，使得部分行显示，部分不显示，导致显示错误。
> 
> **解决方法** ：对于行合并，增加rowSpanKey 属性去兼容，rowSpanKey函数需要返回每组合并行中共用的key值，组件内部会根据key值进行计算并完整显示合并行内容。如你给出的图中，key则为楼层对应的属性值，rowSpanKey(row) { return row[楼层] }。版本为1.13.0
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/19643785/231434476-ce044f8b-acb6-4520-bc10-574b1b69e6fb.png">
> 
> 详细请看demo和源码： https://xiaocheng555.github.io/el-table-virtual-scroll/#/Rowspan?code=Rowspan&codeTitle=%E5%90%88%E5%B9%B6%E8%A1%8C
