### ISSUE TITLE
展开懒加载是否可以支持默认展开

### ISSUE THREAD

**Issue by szmxx** [xiaocheng555/el-table-virtual-scroll#17]
https://xiaocheng555.github.io/el-table-virtual-scroll/#/VTreeDemo?code=VTreeDemo&codeTitle=%E6%A8%A1%E6%8B%9F%E6%A0%91%E7%BB%93%E6%9E%84%E6%87%92%E5%8A%A0%E8%BD%BD

这个demo是否可以支持默认展开某层级，或者多层级

**Comment by xiaocheng555** [comment]
> https://xiaocheng555.github.io/el-table-virtual-scroll/#/VTreeDemo?code=VTreeDemo&codeTitle=%E6%A8%A1%E6%8B%9F%E6%A0%91%E7%BB%93%E6%9E%84%E6%87%92%E5%8A%A0%E8%BD%BD
> 
> 这个demo是否可以支持默认展开某层级，或者多层级

目前不支持

**Comment by szmxx** [comment]
我想了一个思路，你看这样是否可行？
有些代码可以放库内部 ->
https://codesandbox.io/s/youthful-wave-zjzbjk?file=/src/datamap.json:3840093-3840096

**Comment by xiaocheng555** [comment]
> 我想了一个思路，你看这样是否可行？ 有些代码可以放库内部 -> https://codesandbox.io/s/youthful-wave-zjzbjk?file=/src/datamap.json:3840093-3840096

好的，我后续完善一下

**Comment by blue-cave** [comment]
@xiaocheng555 ，哥哥能支持一下ie11吗，这个插件确实很好用

**Comment by xiaocheng555** [comment]
> 我想了一个思路，你看这样是否可行？ 有些代码可以放库内部 -> https://codesandbox.io/s/youthful-wave-zjzbjk?file=/src/datamap.json:3840093-3840096

感谢提供demo!!

现在支持手动展开行：

![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/0aa0910b-1db5-4d90-b0e0-7b3d9234d00d)

并且改了你的demo放在这里了：

https://xiaocheng555.github.io/el-table-virtual-scroll/#/VTreeDemo2?code=VTreeDemo2&codeTitle=%E6%A8%A1%E6%8B%9F%E6%A0%91%E7%BB%93%E6%9E%84%E6%87%92%E5%8A%A0%E8%BD%BD2
