### ISSUE TITLE
使用vuex作为数据中间件的情况下，出现选中展示的问题

### ISSUE THREAD

**Issue by uoiszero** [xiaocheng555/el-table-virtual-scroll#18]
由于vuex修改数据需要通过mutation，所以在绑定数据源的时候我深克隆了数据。
如果这时用户点击了全选按钮，实际被修改了$v_checked属性的是这份克隆数据。
接下来如果用户对数据进行了操作，比如修改了数据的一个属性，就会触发mutation对原始数据进行修改，这时绑定数据源也跟着发生变化，重新克隆了一份。
但是由于原始数据上没有$v_checked字段，所以页面上的checkbox选中状态消失，但是由于没有发生选中变更，所以 @selection-change事件不会被触发。
我现在的处理方式是，在 @selection-change事件中记录下所有数据的id，然后在 @change 事件中依次对数据设置一次$v_checked属性。

**Comment by xiaocheng555** [comment]
> 由于vuex修改数据需要通过mutation，所以在绑定数据源的时候我深克隆了数据。 如果这时用户点击了全选按钮，实际被修改了$v_checked属性的是这份克隆数据。 接下来如果用户对数据进行了操作，比如修改了数据的一个属性，就会触发mutation对原始数据进行修改，这时绑定数据源也跟着发生变化，重新克隆了一份。 但是由于原始数据上没有$v_checked字段，所以页面上的checkbox选中状态消失，但是由于没有发生选中变更，所以 @selection-change事件不会被触发。 我现在的处理方式是，在 @selection-change事件中记录下所有数据的id，然后在 @change 事件中依次对数据设置一次$v_checked属性。

<img width="955" alt="image" src="https://user-images.githubusercontent.com/19643785/233822047-c4bb6239-ed5d-4f86-a9ba-a20d8b5f36ea.png">

可以不用管$v_checked字段，在selection-change事件中返回所有选中的rows数据，记录选中数据ids，然后在页面初始化时，通过ids找到选中rows，调用toggleRowSelection(rows, true)方法让选中表格数据

**Comment by uoiszero** [comment]
已经按照这个解决方案修改，目前没有问题了
