### ISSUE TITLE
能 支持大数据里的列嘛？

### ISSUE THREAD

**Issue by cMing1997** [xiaocheng555/el-table-virtual-scroll#19]
需求：如题
场景：有一个超多列的表格，每一列是采用render形式渲染的

**Comment by xiaocheng555** [comment]
> 需求：如题 场景：有一个超多列的表格，每一列是采用render形式渲染的

不支持列

**Comment by xiaocheng555** [comment]
> 需求：如题 场景：有一个超多列的表格，每一列是采用render形式渲染的

可以试试其他库,如: https://vxetable.cn/v2/#/table/scroll/cols
