### ISSUE TITLE
请教报错，基本按照demo来的

### ISSUE THREAD

**Issue by zyt-cpu** [xiaocheng555/el-table-virtual-scroll#22]
![4](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/65690343/30561dd4-c3dd-4f66-97ea-2e93494766b6)
![5](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/65690343/7304f017-21cb-424c-b1a4-f9e43bb62cbb)

**Comment by xiaocheng555** [comment]
> ![4](https://user-images.githubusercontent.com/65690343/246785281-30561dd4-c3dd-4f66-97ea-2e93494766b6.png) ![5](https://user-images.githubusercontent.com/65690343/246785833-7304f017-21cb-424c-b1a4-f9e43bb62cbb.png)

<img width="669" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/61bda03b-4714-4a70-ab4a-d8f2d2cc8957">
这里大小写没对应上

**Comment by zyt-cpu** [comment]
不报错了，但是数据不显示
![6](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/65690343/e862c388-4b94-403b-b383-46f70895dc62)

**Comment by zyt-cpu** [comment]
有了，感谢
