### ISSUE TITLE
表格会向下平移显示，数据量越大，平移的约多？

### ISSUE THREAD

**Issue by zyt-cpu** [xiaocheng555/el-table-virtual-scroll#23]

**Comment by xiaocheng555** [comment]
不太懂你的意思，有图或者视频吗，代码中怎么使用组件的呢

**Comment by zyt-cpu** [comment]
![7](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/65690343/6127f423-5e77-4385-80c5-fc2d28e52379)
![8](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/65690343/99ee0262-e9cd-4786-91bf-fd8fcbf6cf14)

**Comment by zyt-cpu** [comment]
似乎和:key有关系，我不小心设置了，:key="{height:value==='100%' ? 'calc(100vh-55px-25px)' : ''}"     的时候，显示会变正常，但是会报错，大量重复的错：    key要设置为string或者数字，但是数字和string的话，还是会下移

**Comment by xiaocheng555** [comment]
> 似乎和:key有关系，我不小心设置了，:key="{height:value==='100%' ? 'calc(100vh-55px-25px)' : ''}" 的时候，显示会变正常，但是会报错，大量重复的错： key要设置为string或者数字，但是数字和string的话，还是会下移

key-prop和row-key 不能用 ‘value.id’ 这种对象形式,只能是单个字符串,如 id

**Comment by zyt-cpu** [comment]
这俩不设置的话，还是会下移

**Comment by xiaocheng555** [comment]
> 这俩不设置的话，还是会下移

key-prop 必须设置,唯一标示来的

**Comment by zyt-cpu** [comment]
我设置了一个string作为key-prop，还是会下移？

**Comment by xiaocheng555** [comment]
> 我设置了一个string作为key-prop，还是会下移？

能提供一个demo吗

**Comment by zyt-cpu** [comment]
我自己的一个demo是正常的，加入一个稍大 的项目里显示的是这样

**Comment by xiaocheng555** [comment]
> 我自己的一个demo是正常的，加入一个稍大 的项目里显示的是这样

加我qq：1052745517 ，我可以帮你看看

**Comment by xiaocheng555** [comment]
已解决，设置key-prop，但实际获取到的keyProp值为undfined；改为不使用动态高度:
<virtual-scroll  :item-size="35" :dynamic="false" ...> 就可以
