### ISSUE TITLE
是否可以支持懒加载分页

### ISSUE THREAD

**Issue by nanguantong** [xiaocheng555/el-table-virtual-scroll#24]
针对每一个 child 下有超多的子节点情况，都做一个分页从远端服务获取的功能，类似这样：
<img width="791" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/12180902/9fd2a6cc-23e5-4e18-876c-8b0902832423">

**Comment by xiaocheng555** [comment]
> 针对每一个 child 下有超多的子节点情况，都做一个分页从远端服务获取的功能，类似这样： <img alt="image" width="791" src="https://user-images.githubusercontent.com/12180902/248744304-9fd2a6cc-23e5-4e18-876c-8b0902832423.png">

分页自己实现就行了吧，为什么需要组件支持

**Comment by nanguantong** [comment]
可以参考 [Table Tree](https://cjsound.github.io/vue-table-tree/demo/tree.html)
这里是直接把分页做到组件里

**Comment by xiaocheng555** [comment]
> 可以参考 [Table Tree](https://cjsound.github.io/vue-table-tree/demo/tree.html) 这里是直接把分页做到组件里

不支持这种
