### ISSUE TITLE
el-table开启固定列后滚动会卡顿很严重

### ISSUE THREAD

**Issue by xfmbyc** [xiaocheng555/el-table-virtual-scroll#25]
```html
<virtualScroll
      :data="tableData"
      :itemSize="45"
      keyProp="colGuid"
      @change="data => (renderData = data)"
      @selection-change="selectRows"
    >
      <el-table
        row-key="colGuid"
        :data="renderData"
        :height="tableHeight"
        ref="multipleTable"
        border
        size="small"
        :stripe="isStripe"
        :header-cell-style="headerStyle"
        :cell-style="{ textAlign: 'center' }"
        v-loading="loading"
        element-loading-text="加载中..."
        element-loading-spinner="aic-icon-loading"
      >
        <virtual-column width="55" type="selection"></virtual-column>
        <virtual-column label="序号" align="center" width="80" type="index"></virtual-column>
        <el-table-column prop="itemName" label="名称" min-width="100"> </el-table-column>
        <el-table-column prop="createTime" label="创建时间" min-width="100"> </el-table-column>
        <el-table-column prop="sortNo" label="排序" min-width="100"> </el-table-column>
        <el-table-column label="操作" min-width="100" fixed="right">
          <template slot-scope="scope">
            <el-button
              :disabled="scope.row.status === 1"
              type="primary"
              size="mini"
              icon="el-icon-edit"
              title="详情"
              @click="onDetail(scope)"
            ></el-button>
          </template>
        </el-table-column>
      </el-table>
    </virtualScroll>
```

**Comment by xiaocheng555** [comment]
> ```
> <virtualScroll
>       :data="tableData"
>       :itemSize="45"
>       keyProp="colGuid"
>       @change="data => (renderData = data)"
>       @selection-change="selectRows"
>     >
>       <el-table
>         row-key="colGuid"
>         :data="renderData"
>         :height="tableHeight"
>         ref="multipleTable"
>         border
>         size="small"
>         :stripe="isStripe"
>         :header-cell-style="headerStyle"
>         :cell-style="{ textAlign: 'center' }"
>         v-loading="loading"
>         element-loading-text="加载中..."
>         element-loading-spinner="aic-icon-loading"
>       >
>         <virtual-column width="55" type="selection"></virtual-column>
>         <virtual-column label="序号" align="center" width="80" type="index"></virtual-column>
>         <el-table-column prop="itemName" label="名称" min-width="100"> </el-table-column>
>         <el-table-column prop="createTime" label="创建时间" min-width="100"> </el-table-column>
>         <el-table-column prop="sortNo" label="排序" min-width="100"> </el-table-column>
>         <el-table-column label="操作" min-width="100" fixed="right">
>           <template slot-scope="scope">
>             <el-button
>               :disabled="scope.row.status === 1"
>               type="primary"
>               size="mini"
>               icon="el-icon-edit"
>               title="详情"
>               @click="onDetail(scope)"
>             ></el-button>
>           </template>
>         </el-table-column>
>       </el-table>
>     </virtualScroll>
> ```

有demo吗，我复现不出来

**Comment by xfmbyc** [comment]
@xiaocheng555 列数放多点，越多越明显

**Comment by xiaocheng555** [comment]
> @xiaocheng555 列数放多点，越多越明显

el-table-virtual-scroll@1.0.15 增加了自定义列的，可以试试看没有效果
el-table-virtual-scroll@1.0.15  有点bug，在el-table-virtual-scroll@1.0.16修复了

<img width="974" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/cfe304cf-0f38-4d1f-93d1-5c686f119be4">

参考demo：https://xiaocheng555.github.io/el-table-virtual-scroll/#/VFixedDemo?code=VFixedDemo&codeTitle=%E5%9B%BA%E5%AE%9A%E5%88%97%EF%BC%88%E8%87%AA%E5%AE%9A%E4%B9%89%EF%BC%89
