### ISSUE TITLE
在el-dialog嵌套弹窗中使用时update方法时会报错undefined getBoundingClientRect

### ISSUE THREAD

**Issue by Xc0018** [xiaocheng555/el-table-virtual-scroll#26]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/103631150/750141fb-f21b-453f-86e1-8f28754b8716)
在项目中使用了嵌套el-dialog,第二层中使用表格并update时会获取到el-dialog__wrapper，表格设定了固定高度
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/103631150/93c33c38-6363-40d5-ac8d-1512a069c4b6)

**Comment by xiaocheng555** [comment]
> ![image](https://user-images.githubusercontent.com/103631150/251372220-750141fb-f21b-453f-86e1-8f28754b8716.png) 在项目中使用了嵌套el-dialog,第二层中使用表格并update时会获取到el-dialog__wrapper，表格设定了固定高度 ![image](https://user-images.githubusercontent.com/103631150/251372944-93c33c38-6363-40d5-ac8d-1512a069c4b6.png)

update方法内 this.$el.getBoundingClientRect这个方法为undfined，是不是exceptiohnVisible没有为true，就调用了update方法

**Comment by Xc0018** [comment]
我在excessVisible为true后使用this.$nextTick，但会报错，使用settimeout没问题

**Comment by xiaocheng555** [comment]
> 我在excessVisible为true后使用this.$nextTick，但会报错，使用settimeout没问题
嗯嗯，那应该是表格没有渲染完，那就用settimeout
