### ISSUE TITLE
colum列兼容后 把check列也fixed 滚动时选中的行会错行显示  

### ISSUE THREAD

**Issue by anchuanyuan** [xiaocheng555/el-table-virtual-scroll#27]
整体很强大 有个问题是 有些列fixed后单选 多选使用 ]提供colum列兼容后 把chekc列也fixed 选中的行会错行显示  如果不fixed 这一列又无法固定在开头

**Comment by xiaocheng555** [comment]
> 整体很强大 有个问题是 有些列fixed后单选 多选使用 ]提供colum列兼容后 把chekc列也fixed 选中的行会错行显示 如果不fixed 这一列又无法固定在开头

我试了没有这种情况，有具体的图和组件是怎么用的吗

**Comment by anchuanyuan** [comment]
哦 不好意思 我又尝试了一下  上面说的不太对  是因为当你把鼠标放在fixed列进行滚动的时候 会显得非常卡顿 当如果你在非fixed列没有这个问题  我觉的需要关闭这个issues 重新开另一个issuse 方便你解决 关于鼠标在fiedx列卡顿问题

**Comment by xiaocheng555** [comment]
> 哦 不好意思 我又尝试了一下 上面说的不太对 是因为当你把鼠标放在fixed列进行滚动的时候 会显得非常卡顿 当如果你在非fixed列没有这个问题 我觉的需要关闭这个issues 重新开另一个issuse 方便你解决 关于鼠标在fiedx列卡顿问题


> 哦 不好意思 我又尝试了一下 上面说的不太对 是因为当你把鼠标放在fixed列进行滚动的时候 会显得非常卡顿 当如果你在非fixed列没有这个问题 我觉的需要关闭这个issues 重新开另一个issuse 方便你解决 关于鼠标在fiedx列卡顿问题

你看看这个demo会不会也出现你说的问题：
https://xiaocheng555.github.io/el-table-virtual-scroll/#/FixedDemo?code=FixedDemo&codeTitle=%E5%9B%BA%E5%AE%9A%E8%A1%A8%E6%A0%BC

el-table-virtual-scroll组件包的是element-ui的table组件，fixed是table内的属性，左右固定都会多生成一个表格，可能你的表格也比较复杂，就会造成固定列那里滚动会卡，你可以先排查是什么原因导致的卡。

**Comment by xiaocheng555** [comment]
> 哦 不好意思 我又尝试了一下 上面说的不太对 是因为当你把鼠标放在fixed列进行滚动的时候 会显得非常卡顿 当如果你在非fixed列没有这个问题 我觉的需要关闭这个issues 重新开另一个issuse 方便你解决 关于鼠标在fiedx列卡顿问题

正常说，应该可以使用postion: sticky 来自己实现表格固定，这样就不会生成额外的table，表格内滚动和固定列里滚动也会在同一表格内，能解决你说的卡顿问题

晚点我试下能不能将postion: sticky 实现表格固定做到<virtual-column> 组件内

<img width="1621" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/0ae83d3e-044c-4d22-8618-93dcfc74efd3">
具体可以看下element-plus的固定列

**Comment by xiaocheng555** [comment]
> 哦 不好意思 我又尝试了一下 上面说的不太对 是因为当你把鼠标放在fixed列进行滚动的时候 会显得非常卡顿 当如果你在非fixed列没有这个问题 我觉的需要关闭这个issues 重新开另一个issuse 方便你解决 关于鼠标在fiedx列卡顿问题

el-table-virtual-scroll@1.0.15  增加了自定义列的，可以试试
el-table-virtual-scroll@1.0.15  有点bug，在el-table-virtual-scroll@1.0.16修复了


<img width="1023" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/2c6918ca-f0cf-4ff9-be92-835690d1dbc6">
参考demo：https://xiaocheng555.github.io/el-table-virtual-scroll/#/VFixedDemo?code=VFixedDemo&codeTitle=%E5%9B%BA%E5%AE%9A%E5%88%97%EF%BC%88%E8%87%AA%E5%AE%9A%E4%B9%89%EF%BC%89
