### ISSUE TITLE
virtual-column 不支持selectable去控制checkbox的禁用状态

### ISSUE THREAD

**Issue by songxianzhe** [xiaocheng555/el-table-virtual-scroll#29]
需要为多选框根据条件判断多选是否禁用, virtual-column 不支持使用selectable去控制checkbox的禁用状态, 请问可以支持该属性或新增其他属性去控制吗?

**Comment by songxianzhe** [comment]
<img width="287" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/29993616/ecb7fb4b-6588-4bc6-aade-540f72206e71">

**Comment by songxianzhe** [comment]
```
<virtual-column
  type="selection"
  fixed
  width="55"
  align="center"
  :selectable=" (row, index) => index!==0 "
/>
<el-table-column
  type="selection"
  width="55"
  align="center"
  :selectable=" (row, index) => index!==0 "
/>
```

**Comment by xiaocheng555** [comment]
好的，晚点支持这个功能

**Comment by xiaocheng555** [comment]
> 需要为多选框根据条件判断多选是否禁用, virtual-column 不支持使用selectable去控制checkbox的禁用状态, 请问可以支持该属性或新增其他属性去控制吗?

已支持，el-table-virtual-scroll升级到1.0.17版本
