### ISSUE TITLE
目前不支持树形列表的虚拟滚动，这个支持有计划么？

### ISSUE THREAD

**Issue by yu530feng** [xiaocheng555/el-table-virtual-scroll#3]
目前不支持树形列表的虚拟滚动，这个支持有计划么？

**Comment by xiaocheng555** [comment]
> 目前不支持树形列表的虚拟滚动，这个支持有计划么？

我先看看代码，晚点答复你

**Comment by xiaocheng555** [comment]
> 目前不支持树形列表的虚拟滚动，这个支持有计划么？

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/19643785/207284138-1b83f57f-524f-4e2e-a671-6dec629c05c2.png">

代码已做了兼容，详细看图上demo，你看看能不能满足

**Comment by yu530feng** [comment]
试了，效果不错，很赞！

**Comment by xiaocheng555** [comment]
> 试了，效果不错，很赞！

👌，目前树结构只能做一级节点的虚拟滚动，如果想要所有节点都虚拟滚动可以模拟树结构懒加载，新增了demo
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/19643785/207490415-7dbf49f1-8e2a-4ec0-88d8-e8aba74906bf.png">
