### ISSUE TITLE
如果使用v-show 进行切换表格会特别卡顿

### ISSUE THREAD

**Issue by godic7** [xiaocheng555/el-table-virtual-scroll#30]

**Comment by xiaocheng555** [comment]
怎么使用的，是不是全部数据都渲染了

**Comment by godic7** [comment]
就比如弄了三个页签切换页面,用v-show加载页面组件.然后点哪个页签切换哪个就很卡顿, 用v-show 因为有的时候数据量大了,就不想在加载了

**Comment by xiaocheng555** [comment]
有demo或者代码吗

**Comment by godic7** [comment]
[demo.zip](https://github.com/xiaocheng555/el-table-virtual-scroll/files/12300464/demo.zip)
就类似这个用的main.vue, 只要第一个表格滑动到底部或者操作过东西,在切换就特别卡

**Comment by xiaocheng555** [comment]
> [demo.zip](https://github.com/xiaocheng555/el-table-virtual-scroll/files/12300464/demo.zip) 就类似这个用的main.vue, 只要第一个表格滑动到底部或者操作过东西,在切换就特别卡

已修复，el-table-virtual-scroll升级到1.0.17版本

**Comment by godic7** [comment]
感谢，但是我试了还是有点卡，就用那个demo 已经升级了     "el-table-virtual-scroll": "^1.0.17", 是有什么要配置的吗，就是第一页滑倒最底下，然后再切换这种

**Comment by xiaocheng555** [comment]
> 感谢，但是我试了还是有点卡，就用那个demo 已经升级了 "el-table-virtual-scroll": "^1.0.17", 是有什么要配置的吗，就是第一页滑倒最底下，然后再切换这种

不用配置，你确定一下是不是已经升级到1.0.17了，项目重新跑一下

**Comment by godic7** [comment]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/34437293/ca41e02f-cbad-4a3b-8605-c0443e136951)
淘宝镜像下的有关系吗

**Comment by xiaocheng555** [comment]
> ![image](https://user-images.githubusercontent.com/34437293/259649072-ca41e02f-cbad-4a3b-8605-c0443e136951.png) 淘宝镜像下的有关系吗

<img width="1392" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/bd49182c-7e61-43c7-aa58-424c8b066eac">
我demo里面有个重定向的，你把这个配置却去掉重新跑看看

**Comment by godic7** [comment]
还是不好使, https://registry.npmmirror.com/el-table-virtual-scroll 这个是最新版本吗 https://registry.npmmirror.com/el-table-virtual-scroll/-/el-table-virtual-scroll-1.0.17.tgz, node_modules 删了重下的还是不行

**Comment by xiaocheng555** [comment]
> 还是不好使, https://registry.npmmirror.com/el-table-virtual-scroll 这个是最新版本吗 https://registry.npmmirror.com/el-table-virtual-scroll/-/el-table-virtual-scroll-1.0.17.tgz, node_modules 删了重下的还是不行

https://xiaocheng555.github.io/el-table-virtual-scroll/#/VSelectionDemo?code=VSelectionDemo&codeTitle=%E5%A4%9A%E9%80%89

<img width="1275" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/5af2694e-fc4a-4870-8ebe-a7146258ba26">

这个demo，你点击显示隐藏看看会不会卡顿，然后你在本地代码按这样写看会不会卡顿

**Comment by godic7** [comment]
本地这么写不会卡,你主要试试那个我的那个切换的demo就是从第一个滑动到底部 第二也滑到底部,然后互相切换就会卡

**Comment by xiaocheng555** [comment]
[vtable.zip](https://github.com/xiaocheng555/el-table-virtual-scroll/files/12311382/vtable.zip)

你看看这个demo，我试了不会卡顿

**Comment by xiaocheng555** [comment]
> 本地这么写不会卡,你主要试试那个我的那个切换的demo就是从第一个滑动到底部 第二也滑到底部,然后互相切换就会卡

**Comment by godic7** [comment]
感谢你的一直回复, 是main.vue 是吧, 我试了还是会卡,是浏览器不一样吗 就是滑动完之后切换页签明显卡顿, 我用的浏览器edge 113.0.1774.50

**Comment by xiaocheng555** [comment]
> 感谢你的一直回复, 是main.vue 是吧, 我试了还是会卡,是浏览器不一样吗 就是滑动完之后切换页签明显卡顿, 我用的浏览器edge 113.0.1774.50

升级到 el-table-virtual-scroll@1.0.18 试试

**Comment by godic7** [comment]
可以了，强
