### ISSUE TITLE
使用自定义固定列，当表格不存在滚动条时，表头偏移

### ISSUE THREAD

**Issue by fengqingyin** [xiaocheng555/el-table-virtual-scroll#31]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/42838592/c026c6b3-d983-4a86-b054-ce589cdd8f23)
看了下是使用的right:10px 来使表头右侧空出滚动条的位置，但是当滚动条不存在时，没进行还原

**Comment by xiaocheng555** [comment]
> ![image](https://user-images.githubusercontent.com/42838592/259951235-c026c6b3-d983-4a86-b054-ce589cdd8f23.png) 看了下是使用的right:10px 来使表头右侧空出滚动条的位置，但是当滚动条不存在时，没进行还原

什么情况下会没有滚动条，怎么复现这种情况

**Comment by fengqingyin** [comment]
数据行数少，就不会出现滚动条啊。超过高度才会出现滚动条。

**Comment by xiaocheng555** [comment]
> 数据行数少，就不会出现滚动条啊。超过高度才会出现滚动条。

修复了，升级到1.0.19 试试
