### ISSUE TITLE
切换固定列，导致显示条数计算错误

### ISSUE THREAD

**Issue by donnyzxt** [xiaocheng555/el-table-virtual-scroll#32]
VitualColumn的fixed属性被改变后，原先获取的scroller从dom中消失，计算显示条数时候，需要重新获取。建议减轻fixed属性，变化后重新获取scroller。

**Comment by xiaocheng555** [comment]
> VitualColumn的fixed属性被改变后，原先获取的scroller从dom中消失，计算显示条数时候，需要重新获取。建议减轻fixed属性，变化后重新获取scroller。

不太懂你的意思,有代码或者图片吗

**Comment by donnyzxt** [comment]
重现方法是代码动态切换字段的fixed，然后scroll对应的dom就从页面上找不到了，后边计算就错了。修改fixed后，el-table回重新绘制整个组件。

**Comment by xiaocheng555** [comment]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/5d57faab-734d-494d-b615-0453d2223838)

https://xiaocheng555.github.io/el-table-virtual-scroll/#/CaseDemo?code=CaseDemo&codeTitle=%E6%A1%88%E4%BE%8B
在这个页面，你说的问题是这里切换固定列时，固定列的滚动位置不对，有偏移是吗


> 重现方法是代码动态切换字段的fixed，然后scroll对应的dom就从页面上找不到了，后边计算就错了。修改fixed后，el-table回重新绘制整个组件。

**Comment by donnyzxt** [comment]
fixed从''转成'left'，逻辑中就会重新计算展示范围，但是因为scroll的dom元素被vue重新绘制了，之前存的那个scroll对象需要重新拿一下。

**Comment by xiaocheng555** [comment]
> fixed从''转成'left'，逻辑中就会重新计算展示范围，但是因为scroll的dom元素被vue重新绘制了，之前存的那个scroll对象需要重新拿一下。

切换fixed不会重绘整个表格，只会重新渲染表格内的数据，scroller没有变化的

**Comment by xiaocheng555** [comment]
> fixed从''转成'left'，逻辑中就会重新计算展示范围，但是因为scroll的dom元素被vue重新绘制了，之前存的那个scroll对象需要重新拿一下。

调用下面方法可以可以重新刷新scroller：
 this.$refs.virtualScroll.initData()
