### ISSUE TITLE
`virtual-column`如何在设置`vfixed`的情况下自定义el-table的`headerCellStyle`/`cellStyle`

### ISSUE THREAD

**Issue by HYliangkai** [xiaocheng555/el-table-virtual-scroll#33]
如题,vfixed只有在使用了插槽给的`headerCellStyle`/`cellStyle`的情况下才能设置成功.但是如果想要给headerCellStyle,cellStyle加入自己的样式(行高,背景色等...)该如何实现
<img width="1091" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/56477361/dff36c51-88e5-496b-aac4-453affd05033">

**Comment by xiaocheng555** [comment]
> 如题,vfixed只有在使用了插槽给的`headerCellStyle`/`cellStyle`的情况下才能设置成功.但是如果想要给headerCellStyle,cellStyle加入自己的样式(行高,背景色等...)该如何实现 <img alt="image" width="1091" src="https://user-images.githubusercontent.com/56477361/262518195-dff36c51-88e5-496b-aac4-453affd05033.png">

类似这样写：
:cellStyle="(data) => ({ ...cellFixedStyle(data), color: 'red', myCellStyle(data)})"

**Comment by xiaocheng555** [comment]
> 如题,vfixed只有在使用了插槽给的`headerCellStyle`/`cellStyle`的情况下才能设置成功.但是如果想要给headerCellStyle,cellStyle加入自己的样式(行高,背景色等...)该如何实现 <img alt="image" width="1091" src="https://user-images.githubusercontent.com/56477361/262518195-dff36c51-88e5-496b-aac4-453affd05033.png">

试一下上面的方法，看行吗

**Comment by HYliangkai** [comment]
> > 如题,vfixed只有在使用了插槽给的`headerCellStyle`/`cellStyle`的情况下才能设置成功.但是如果想要给headerCellStyle,cellStyle加入自己的样式(行高,背景色等...)该如何实现 <img alt="image" width="1091" src="https://user-images.githubusercontent.com/56477361/262518195-dff36c51-88e5-496b-aac4-453affd05033.png">
> 
> 试一下上面的方法，看行吗
有效,谢谢大大
