### ISSUE TITLE
虚拟滚动固定列在火狐52 32位版本中失效的问题

### ISSUE THREAD

**Issue by codedog01** [xiaocheng555/el-table-virtual-scroll#36]
小哥你好，最近有个新客户，使用的浏览器版本很低，之前用的el-table，数据量太大，又不想要分页，所以使用了[el-table-virtual-scroll]，

但是现在固定列失效了，想问一下有没有什么解决思路呢？

**Comment by xiaocheng555** [comment]
> 小哥你好，最近有个新客户，使用的浏览器版本很低，之前用的el-table，数据量太大，又不想要分页，所以使用了[el-table-virtual-scroll]，
> 
> 但是现在固定列失效了，想问一下有没有什么解决思路呢？

![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/ceba93ef-ad79-486b-883f-449db185ff2c)
用了vfixed吗，用的是sticky，低版本浏览器不支持
只能用回element-ui的fixed
