### ISSUE TITLE
项目打包报错

### ISSUE THREAD

**Issue by blue-cave** [xiaocheng555/el-table-virtual-scroll#38]
win10，vue2.6，webpack2.6，nodeV14
在安装启动以及热部署的时候都没有问题，但是在npm run build打包之后，会产生一个报错
 "el-table-virtual-scroll": "^1.0.20",
```
ERROR in static/js/0.752c5439a0eef37cc905.js from UglifyJs
Unexpected token: name (hook) [./~/el-table-virtual-scroll/dist/el-table-virtual-scroll.esm.js:1422,0][static/js/0.752c5439a0eef37cc905.js:6900,8]
```
![123](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/54425625/d69a581d-ad44-4753-95fb-38bd1da8e724)

**Comment by xiaocheng555** [comment]
> win10，vue2.6，webpack2.6，nodeV14 在安装启动以及热部署的时候都没有问题，但是在npm run build打包之后，会产生一个报错 "el-table-virtual-scroll": "^1.0.20",
> 
> ```
> ERROR in static/js/0.752c5439a0eef37cc905.js from UglifyJs
> Unexpected token: name (hook) [./~/el-table-virtual-scroll/dist/el-table-virtual-scroll.esm.js:1422,0][static/js/0.752c5439a0eef37cc905.js:6900,8]
> ```
> 
> ![123](https://user-images.githubusercontent.com/54425625/280239863-d69a581d-ad44-4753-95fb-38bd1da8e724.png)

试下排除 el-table-virtual-scroll.esm.js 文件：
```js
module.exports = {
  // ...
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        exclude: /el-table-virtual-scroll\.esm\.js/
      })
    ]
  }
}
```

**Comment by blue-cave** [comment]
我又试了一下，虽然打包的之后报错，但是项目部署之后时可以使用的，不受影响，但IE浏览器好像不能用

**Comment by xiaocheng555** [comment]
> 我又试了一下，虽然打包的之后报错，但是项目部署之后时可以使用的，不受影响，但IE浏览器好像不能用

ie还没有兼容

**Comment by blue-cave** [comment]
> > 我又试了一下，虽然打包的之后报错，但是项目部署之后时可以使用的，不受影响，但IE浏览器好像不能用
> 
> ie还没有兼容

好的，明白了
