### ISSUE TITLE
virtual-column不支持多表头

### ISSUE THREAD

**Issue by vjguo** [xiaocheng555/el-table-virtual-scroll#39]
想所有列都用virtual-column替代el-table-column,
但目前嵌套virtual-column行为有问题。

el-table-column默认插槽 和 default 的作用域插槽 行为不一样。
el-table-column用作用域插槽嵌套不能实现多表头。
virtual-column只提供了default作用域插槽。

**Comment by xiaocheng555** [comment]
> 想所有列都用virtual-column替代el-table-column, 但目前嵌套virtual-column行为有问题。
> 
> el-table-column默认插槽 和 default 的作用域插槽 行为不一样。 el-table-column用作用域插槽嵌套不能实现多表头。 virtual-column只提供了default作用域插槽。

已支持，升级el-table-virtual-scroll@1.0.21 版本

**Comment by vjguo** [comment]
现在好像渲染模板的时候，有个阶段获取不到作用域插槽参数。
导致获取作用域插槽参数row上的字段时，报undefined错误。

**Comment by vjguo** [comment]
> > 想所有列都用virtual-column替代el-table-column, 但目前嵌套virtual-column行为有问题。
> > el-table-column默认插槽 和 default 的作用域插槽 行为不一样。 el-table-column用作用域插槽嵌套不能实现多表头。 virtual-column只提供了default作用域插槽。
> 
> 已支持，升级el-table-virtual-scroll@1.0.21 版本

现在好像渲染模板的时候，有个阶段获取不到作用域插槽参数。
导致获取作用域插槽参数row上的字段时，报undefined错误。
