### ISSUE TITLE
大佬，我现在用的框架是ant design vue 1.x的版本，500条数据一页，全选啥的贼卡

### ISSUE THREAD

**Issue by LiJunXiao** [xiaocheng555/el-table-virtual-scroll#4]
您考虑出一个ant design vue的版本嘛？

**Comment by xiaocheng555** [comment]
> 
我看ant design vue 有一个Surely Vue库，也是有虚拟滚动的，你可以试试那个
https://surely.cool/doc/basic

**Comment by xiaocheng555** [comment]
> 您考虑出一个ant design vue的版本嘛？

Surely Vue 是vue3的😂

**Comment by LiJunXiao** [comment]
是的，目前我们的这个是vue2的，您这个是vue2可以用的嘛？我如果直接用您这个，我是不是还需要引入element ui的依赖啊？

**Comment by xiaocheng555** [comment]
> 是的，目前我们的这个是vue2的，您这个是vue2可以用的嘛？我如果直接用您这个，我是不是还需要引入element ui的依赖啊？

是vue2的，需要引入element ui的依赖，可以在全局按需引入依赖的Checkbox, Radio, Table, TableColumn 组件，如：
 import { Checkbox, Radio, Table, TableColumn } from 'element-ui'
Vue.use(Checkbox)
Vue.use(Radio)
Vue.use(Table)
Vue.use(TableColumn)

**Comment by LiJunXiao** [comment]
大佬，您这个组件,yarn 可以安装么？

**Comment by xiaocheng555** [comment]
> 大佬，您这个组件,yarn 可以安装么？

可以的，yarn add el-table-virtual-scroll -S。
另外，我试试写一下ant design vue 的虚拟表格

**Comment by xiaocheng555** [comment]
> 大佬，您这个组件,yarn 可以安装么？

ant design vue的虚拟表格粗略写完了，支持常用的使用场景，可以试试能不能满足，后期有时间再完善
https://github.com/xiaocheng555/a-virtual-table
