### ISSUE TITLE
支持vue3

### ISSUE THREAD

**Issue by SukiyakiWind** [xiaocheng555/el-table-virtual-scroll#40]
有没有考虑支持vue3，如果想在vue3 + elementPlus 中使用是不是只能手动复制代码然后修改呢

**Comment by xiaocheng555** [comment]
> 有没有考虑支持vue3，如果想在vue3 + elementPlus 中使用是不是只能手动复制代码然后修改呢

https://github.com/xiaocheng555/el-table-virtual-scroll-next  这个试试
