### ISSUE TITLE
使用virtual-column组件使用formatter参数不生效

### ISSUE THREAD

**Issue by george-hong** [xiaocheng555/el-table-virtual-scroll#41]
作者你好：
    使用virtual-column组件时，组件内部实现一定会给el-table-column传入default插槽，导致formatter参数不会生效。
这个能否多加个判断呢？
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/29765615/58dec22c-4843-4736-9ecf-0713847b577d)

**Comment by xiaocheng555** [comment]
> 作者你好： 使用virtual-column组件时，组件内部实现一定会给el-table-column传入default插槽，导致formatter参数不会生效。 这个能否多加个判断呢？ ![image](https://user-images.githubusercontent.com/29765615/284887965-58dec22c-4843-4736-9ecf-0713847b577d.png)

感谢提交修复代码，已经发布到1.0.22
