### ISSUE TITLE
column中加入el-input-number，输入框中的数字渲染会有问题

### ISSUE THREAD

**Issue by hikuyaya** [xiaocheng555/el-table-virtual-scroll#43]
https://github.com/xiaocheng555/el-table-virtual-scroll/assets/15666890/c8a16cd2-9299-4e05-8f0f-8f4e2594c7d6

如我在某一行输入10，在输入框获取焦点的状态下，往下滚动页面，10会渲染到其他行

**Comment by hikuyaya** [comment]
https://github.com/xiaocheng555/el-table-virtual-scroll/assets/15666890/4f6f6520-b604-47ec-b5fc-7eaf23dc0038

**Comment by xiaocheng555** [comment]
> QQ.20231123155423.mp4 
> 如我在某一行输入10，在输入框获取焦点的状态下，往下滚动页面，10会渲染到其他行

给 `<el-table>` 加上 row-key="xxx" ，xxx唯一值key值

**Comment by hikuyaya** [comment]
> > QQ.20231123155423.mp4
> > 如我在某一行输入10，在输入框获取焦点的状态下，往下滚动页面，10会渲染到其他行
> 
> 给 `<el-table>` 加上 row-key="xxx" ，xxx唯一值key值


感谢！之前的代码是把row-key加到`<virtual-scroll>`上了，加到`<el-table>`上好了
