### ISSUE TITLE
树结构懒加载 如果有hasChildren=false的行 行可视区域高度异常

### ISSUE THREAD

**Issue by vjguo** [xiaocheng555/el-table-virtual-scroll#45]
如题 请问树形懒加载是否支持初始指定行不含有子节点？
当table设置lazy和load 绑定的data中含有hasChildren=false的行时
表格可视区域整体变低了

**Comment by xiaocheng555** [comment]
> 如题 请问树形懒加载是否支持初始指定行不含有子节点？ 当table设置lazy和load 绑定的data中含有hasChildren=false的行时 表格可视区域整体变低了

已修复问题：当table设置lazy和load 绑定的data中含有hasChildren=false的行时表格可视区域整体变低了
升级版本 1.0.24
