### ISSUE TITLE
VirtualColumn使用默认作用域插槽渲染模板过程中有获取不到作用于插槽参数的阶段

### ISSUE THREAD

**Issue by vjguo** [xiaocheng555/el-table-virtual-scroll#46]
在模板中不判断非空直接使用默认作用域插槽参数row的字段，会报尝试获取undefined上的属性的错误。

**Comment by xiaocheng555** [comment]
> 在模板中不判断非空直接使用默认作用域插槽参数row的字段，会报尝试获取undefined上的属性的错误。

http://localhost:8080/#/HeaderDemo2?code=HeaderDemo2&codeTitle=head
demo没复现出来

**Comment by vjguo** [comment]
> > 在模板中不判断非空直接使用默认作用域插槽参数row的字段，会报尝试获取undefined上的属性的错误。
> 
> http://localhost:8080/#/HeaderDemo2?code=HeaderDemo2&codeTitle=head demo没复现出来

我又试了下，换回ElTableColumn不报错，只有用VirtualColumn报错。
具体原因我还没找到，找到后我再回复。

**Comment by vjguo** [comment]
https://github.com/xiaocheng555/el-table-virtual-scroll/blob/master/src/el-table-virtual-column.vue#L288

**Comment by vjguo** [comment]
猜测是这样
https://github.com/xiaocheng555/el-table-virtual-scroll/blob/master/src/el-table-virtual-column.vue#L288
created钩子里 $scopedSlots还没初始化完 应该没有default插槽 isNested值恒常为true
导致上面https://github.com/xiaocheng555/el-table-virtual-scroll/blob/master/src/el-table-virtual-column.vue#L24
默认插槽渲染 而下面作用域插槽没渲染 此时获取作用域插槽参数为空 报错
如果判断非空了 等$scopedSlots有值了 就又能获取到作用域插槽参数了 所以能够变回显示正常

demo不复现的原因不太清楚 希望能确认下isNested的值是否正确的问题

**Comment by vjguo** [comment]
https://github.com/xiaocheng555/el-table-virtual-scroll/blob/master/src/el-table-virtual-column.vue#L241
另外这一行代码 取反操作符的位置是不是不太对？

**Comment by vjguo** [comment]
Element里有一种判断isNested的写法 是否能作为参考？
https://github.com/ElemeFE/element/blob/dev/packages/form/src/form-item.vue#L140

**Comment by xiaocheng555** [comment]
> Element里有一种判断isNested的写法 是否能作为参考？ https://github.com/ElemeFE/element/blob/dev/packages/form/src/form-item.vue#L140

ok

**Comment by xiaocheng555** [comment]
> 猜测是这样 https://github.com/xiaocheng555/el-table-virtual-scroll/blob/master/src/el-table-virtual-column.vue#L288 created钩子里 $scopedSlots还没初始化完 应该没有default插槽 isNested值恒常为true 导致上面https://github.com/xiaocheng555/el-table-virtual-scroll/blob/master/src/el-table-virtual-column.vue#L24 默认插槽渲染 而下面作用域插槽没渲染 此时获取作用域插槽参数为空 报错 如果判断非空了 等$scopedSlots有值了 就又能获取到作用域插槽参数了 所以能够变回显示正常
> 
> demo不复现的原因不太清楚 希望能确认下isNested的值是否正确的问题

你有必现的demo吗

**Comment by vjguo** [comment]
我这边仅这样就可以复现了。

      <VirtualScroll :data="[]">
        <el-table>
        <VirtualColumn label="test">
          <template #default="{ row }">
            
            
            {{ row.test }}
          </template>
        </VirtualColumn>
        </el-table>
      </VirtualScroll>

**Comment by xiaocheng555** [comment]
> 我这边仅这样就可以复现了。
> 
> ```
>   <VirtualScroll :data="[]">
>     <el-table>
>     <VirtualColumn label="test">
>       <template #default="{ row }">
>         
>         
>         {{ row.test }}
>       </template>
>     </VirtualColumn>
>     </el-table>
>   </VirtualScroll>
> ```

我改了另一种写法，你看看会不会报undefined（我demo复现不出来），升级版本 1.0.25
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/2ad1357e-5b30-4f10-a04d-3b4d0e44a03a)

**Comment by vjguo** [comment]
> > 我这边仅这样就可以复现了。
> > ```
> >   <VirtualScroll :data="[]">
> >     <el-table>
> >     <VirtualColumn label="test">
> >       <template #default="{ row }">
> >         
> >         
> >         {{ row.test }}
> >       </template>
> >     </VirtualColumn>
> >     </el-table>
> >   </VirtualScroll>
> > ```
> 
> 我改了另一种写法，你看看会不会报undefined（我demo复现不出来），升级版本 1.0.25 ![image](https://private-user-images.githubusercontent.com/19643785/286577360-2ad1357e-5b30-4f10-a04d-3b4d0e44a03a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTAxNTYsIm5iZiI6MTcwMTMwOTg1NiwicGF0aCI6Ii8xOTY0Mzc4NS8yODY1NzczNjAtMmFkMTM1N2UtNWIzMC00ZjEwLWEwNGQtM2I0ZDBlNDRhMDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAyMDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYWZkN2Y3NmQyMjc4MzliZGE0YjU3OTk5YmYyN2JhNmE1N2NmYzVjNDBhODMwNTg2NDM5NzljMTI5NjkzYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yHMzanhLE9-zZWVTmVxYcy9wnQbyomjRJxxJZLgSjlY)

升级后我这边不报错可以正常使用了，感谢！
