### ISSUE TITLE
貌似不支持 highlight-selection-row 选中高亮

### ISSUE THREAD

**Issue by shunyue1320** [xiaocheng555/el-table-virtual-scroll#48]
<el-table highlight-selection-row @row-click="fn">
  <virtual-column fixed="left" type="selection" width="55"></virtual-column>

**Comment by xiaocheng555** [comment]
> <el-table highlight-selection-row @row-click="fn">

ok，我兼容一下

**Comment by xiaocheng555** [comment]
> <el-table highlight-selection-row @row-click="fn">

兼容不了，得自己加高亮class：
```
<el-table :row-class-name="getRowClassName">...

getRowClassName ({row}) {
      // 选中行高亮
      if (row.$v_checked) {
        return 'selection-row'
      }
    }
```

**Comment by xiaocheng555** [comment]
https://xiaocheng555.github.io/el-table-virtual-scroll/#/VSelectionDemo?code=VSelectionDemo&codeTitle=%E5%A4%9A%E9%80%89
参考demo

**Comment by shunyue1320** [comment]
感谢
