### ISSUE TITLE
含固定列表格，由display:none切换为显示时，固定列高度闪动

### ISSUE THREAD

**Issue by vjguo** [xiaocheng555/el-table-virtual-scroll#49]
DEMO通过控制台开启关闭display:none样式可复现。

**Comment by vjguo** [comment]
https://xiaocheng555.github.io/el-table-virtual-scroll/#/FixedDemo?code=FixedDemo&codeTitle=%E5%9B%BA%E5%AE%9A%E5%88%97

**Comment by vjguo** [comment]
固定列(自定义)感觉使用起来各方面都很不错，准备切到那个方案。

**Comment by xiaocheng555** [comment]
> DEMO通过控制台开启关闭display:none样式可复现。

要设置fit为false，`<el-table :fit="false">`，fit为true的时候display从none切换为block会重新计算列，滚动位置也会重置到顶部
