### ISSUE TITLE
有没有开启和关闭虚拟滚动的props？

### ISSUE THREAD

**Issue by MaJiaXuan** [xiaocheng555/el-table-virtual-scroll#5]
有没有开启和关闭虚拟滚动的props？

**Comment by xiaocheng555** [comment]
> 有没有开启和关闭虚拟滚动的props？

暂时没有，后续再补充.使用场景是不是数据量大于100条时开启虚拟滚动，不够100条则不开启

**Comment by xiaocheng555** [comment]
> 有没有开启和关闭虚拟滚动的props？

<img width="1762" alt="image" src="https://user-images.githubusercontent.com/19643785/211236040-94a30fa5-4526-4316-8f6c-13918a2f3c58.png">
<img width="934" alt="image" src="https://user-images.githubusercontent.com/19643785/211238252-c5b03a76-ece0-4d22-a0d2-9615ee82f7b0.png">

已增加prop virtualized 控制是否开启虚拟滚动
