### ISSUE TITLE
表头列宽拖拽使表头高度变化后，显示区域高度计算异常。

### ISSUE THREAD

**Issue by vjguo** [xiaocheng555/el-table-virtual-scroll#50]
(https://xiaocheng555.github.io/el-table-virtual-scroll/#/BasicDemo?code=BasicDemo&codeTitle=%E5%9F%BA%E7%A1%80%E8%A1%A8%E6%A0%BC)

有横向滚动条的时候更明显。
![屏幕截图 2023-11-30 175341](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/70465895/92dd94bf-4d00-4ed6-b622-8cd97c694b63)

**Comment by xiaocheng555** [comment]
> (https://xiaocheng555.github.io/el-table-virtual-scroll/#/BasicDemo?code=BasicDemo&codeTitle=%E5%9F%BA%E7%A1%80%E8%A1%A8%E6%A0%BC)
> 
> 有横向滚动条的时候更明显。 ![屏幕截图 2023-11-30 175341](https://private-user-images.githubusercontent.com/70465895/286889032-92dd94bf-4d00-4ed6-b622-8cd97c694b63.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDI1ODcsIm5iZiI6MTcwMTM0MjI4NywicGF0aCI6Ii83MDQ2NTg5NS8yODY4ODkwMzItOTJkZDk0YmYtNGQwMC00ZWQ2LWI2MjItOGNkOTdjNjk0YjYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDExMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGE3NTMwMGM3M2Q0NmZmOTc4ZDI4MDRkNTE4MjkwNjViMGM1YjJjZjAxNTJmYzA3M2JkOWUyMzNlOGE3MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JSvQOb-yqAxDrMeOs8Bp5PQwA2cI0wGLM9UH2MSWK3o)

element-ui 原表格也会这样
