### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by H-xiaoyu** [xiaocheng555/el-table-virtual-scroll#52]
虚拟表格的keyProp  唯一值能否支持多列，有需求是多列来确定唯一值

**Comment by george-hong** [comment]
这种情况建议在取得数据后先手动组合字段形成唯一id，然后再传入组件

**Comment by xiaocheng555** [comment]
> 这种情况建议在取得数据后先手动组合字段形成唯一id，然后再传入组件

对的

**Comment by xiaocheng555** [comment]
> 虚拟表格的keyProp 唯一值能否支持多列，有需求是多列来确定唯一值

不做支持
