### ISSUE TITLE
貌似不支持 highlight-current-row 选中高亮？

### ISSUE THREAD

**Issue by hikuyaya** [xiaocheng555/el-table-virtual-scroll#53]
没有单选、多选，就单击选中 高亮那一行

**Comment by xiaocheng555** [comment]
> 没有单选、多选，就单击选中 高亮那一行

有用最新版本 1.0.30吗，demo上是可以的
https://xiaocheng555.github.io/el-table-virtual-scroll/#/Highlight?code=Highlight&codeTitle=%E8%A1%8C%E9%AB%98%E4%BA%AE-%E5%8D%95%E9%80%89

**Comment by hikuyaya** [comment]
更新到最新版本可以了，感谢
