### ISSUE TITLE
当树形数据有多层children嵌套时，数量达到上千行时，就会很卡顿了

### ISSUE THREAD

**Issue by yu530feng** [xiaocheng555/el-table-virtual-scroll#54]
遇到：当树形数据有多层children嵌套时，各级加载展开后，数量达到上千行时，就会很卡顿了  
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/8703634/be5b5955-a3a6-4123-8dbc-e619488e7c06)
看原因还是视窗内行数太多了，不知道有没有解决方案

**Comment by xiaocheng555** [comment]
> 遇到：当树形数据有多层children嵌套时，各级加载展开后，数量达到上千行时，就会很卡顿了 ![image](https://private-user-images.githubusercontent.com/8703634/290756058-be5b5955-a3a6-4123-8dbc-e619488e7c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MjYyNTksIm5iZiI6MTcwMjYyNTk1OSwicGF0aCI6Ii84NzAzNjM0LzI5MDc1NjA1OC1iZTViNTk1NS1hM2E2LTQxMjMtOGRiYy1lNjE5NDg4ZTdjMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMDczOTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI0YzI5NGYzNGJlNWY4NmNlMmI2NmMwNGYyYzVkZWJhM2VlOTFiMDk5NzRkYmJiNmQ1MzcxNzBiMmE2MTllMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.roZLNnQwamkevEq-IPDUbLXv7fATrStVCItH0acZXls) 看原因还是视窗内行数太多了，不知道有没有解决方案

树结构虚拟滚动只对一级节点有效，如果有多层children嵌套可能是渲染在页面的dom太多导致卡顿，可以看下面这个demo
https://xiaocheng555.github.io/el-table-virtual-scroll/#/VTreeDemo?code=VTreeDemo&codeTitle=%E6%A8%A1%E6%8B%9F%E6%A0%91%E7%BB%93%E6%9E%84%E6%87%92%E5%8A%A0%E8%BD%BD

**Comment by yu530feng** [comment]
是的，问题原因就出在这里：树结构虚拟滚动只计算一级节点渲染的数据    一级节点下有太多子节点了

**Comment by xiaocheng555** [comment]
> 是的，问题原因就出在这里：树结构虚拟滚动只计算一级节点渲染的数据 一级节点下有太多子节点了

<img width="830" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/242862f5-a527-4c47-afe9-95c7d62985ea">
模拟表格树，不用element-ui的树结构
