### ISSUE TITLE
多级表头+复选框+序号列同时使用，加载表格时会丢失复选框和序号

### ISSUE THREAD

**Issue by Yyc1537** [xiaocheng555/el-table-virtual-scroll#55]
https://github.com/xiaocheng555/el-table-virtual-scroll/assets/129500235/058044b7-2201-4f89-9a4c-fce2e6436b75

不知道是不是嵌套生成的原因
这样没问题
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/129500235/8d1adad6-de30-4540-89b7-29760b55b441)
这样就有问题
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/129500235/b328641b-4393-431c-b0f7-d619b045871d)
有没有正确的使用示例

**Comment by xiaocheng555** [comment]
> 20231221-181245.mp4 
> 不知道是不是嵌套生成的原因 这样没问题 ![image](https://private-user-images.githubusercontent.com/129500235/292170511-8d1adad6-de30-4540-89b7-29760b55b441.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTQ2MjEsIm5iZiI6MTcwMzE1NDMyMSwicGF0aCI6Ii8xMjk1MDAyMzUvMjkyMTcwNTExLThkMWFkYWQ2LWRlMzAtNDU0MC04OWI3LTI5NzYwYjU1YjQ0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQxMDI1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjYwNThmMWQzYjFhMjIyNjE5NDk0YjE4YzJlNmEyNjMzZGNlZjIyMzVmNzVhMTJkZTdjZjdlYzE0YTBkMGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n3JQJBLJwlGeO2POs3QqMBZ7HcaWfoBzKF5h7KXDngY) 这样就有问题 ![image](https://private-user-images.githubusercontent.com/129500235/292170572-b328641b-4393-431c-b0f7-d619b045871d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTQ2MjEsIm5iZiI6MTcwMzE1NDMyMSwicGF0aCI6Ii8xMjk1MDAyMzUvMjkyMTcwNTcyLWIzMjg2NDFiLTQzOTMtNDMxYy1iMGY3LWQ2MTliMDQ1ODcxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQxMDI1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzVmN2EzYzIxYzRkYjkzYThjOTlmMjMyYTIyYzRlZTJjYjA1NGI2ODk4ODI4ZDk3YjcwNDM5ZTY5NDc5ZTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G9fgrjy0-uZGE9nJEBRNg9U_qwkFA6YU09HyQefnLHA) 有没有正确的使用示例

<compoent> 组件是怎么样的

**Comment by Yyc1537** [comment]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/129500235/5000cd8c-6a97-44ec-91ce-4205de088259)
代码太多，大概就是这样，嵌套使用组件，多表头又再生成一次

**Comment by xiaocheng555** [comment]
方便写个demo吗

**Comment by xiaocheng555** [comment]
> ![image](https://private-user-images.githubusercontent.com/129500235/292175815-5000cd8c-6a97-44ec-91ce-4205de088259.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTcwMzksIm5iZiI6MTcwMzE1NjczOSwicGF0aCI6Ii8xMjk1MDAyMzUvMjkyMTc1ODE1LTUwMDBjZDhjLTZhOTctNDRlYy05MWNlLTQyMDVkZTA4ODI1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQxMTA1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDRlNDAxNWM0ZmE5NGQyMDZlNGY2OWY4NzY1NWE3ZTBmYmY1OWM1Y2JjZjE1NzExNTU1NDVjYjFlNmMxMTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-5AW8ckLbLcmNZVdTW-b3J2OUiQefInVa6DYK6DbgqE) 代码太多，大概就是这样，嵌套使用组件，多表头又再生成一次

没有复现出来
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/bd13b205-c87f-4d09-a5a6-aabed8b96e37)


``` vue
// complex1.vue
<template>
  <div>
    <virtual-scroll
      ref="virtualScroll"
      :data="list"
      :item-size="62"
      key-prop="id"
      @change="(virtualList) => tableData = virtualList">
      <el-table
        :data="tableData"
        height="800"
        row-key="id"
        style="width: 100%">
        <virtual-column fixed width="60" type="selection"></virtual-column>
        <virtual-column fixed label="索引" width="80" type="index"></virtual-column>
        <virtual-column type="expand" >
          <template slot-scope="scope">
            {{ scope.row.text }}
          </template>
        </virtual-column>
        <el-table-column
          prop="date"
          label="日期"
          width="150">
        </el-table-column>
        <template v-for="(column, index) in columns">
          <ComplexColum
            :column="column"
            :key="index">
          </ComplexColum>
        </template>
      </el-table>
    </virtual-scroll>
  </div>
</template>

<script>
import VirtualScroll, { VirtualColumn } from 'el-table-virtual-scroll'
import { mockData } from '@/utils'
import ComplexColum from './complexColum1'

export default {
  components: {
    VirtualScroll,
    VirtualColumn,
    ComplexColum
  },
  data () {
    return {
      list: mockData(0, 2000),
      tableData: [],
      columns: [
        {
          title: '内容',
          prop: 'text',
          width: 400
        },
        {
          title: '合并列',
          columns: [
            {
              width: 200,
              title: '地址',
              prop: 'address'
            },
            {
              width: 200,
              title: '名称',
              prop: 'name'
            },
            {
              width: 100,
              title: 'id',
              prop: 'id'
            }
          ]
        },
        {
          title: '内容2',
          prop: 'text2',
          width: 400,
        },
        {
          title: '名称',
          prop: 'name'
        }
      ]
    }
  },
  methods: {

  },
  created () {
  }
}
</script>

<style lang='less' scoped>

</style>

```

``` vue
// complexColum1.vue
<template>
  <el-table-column :width="column.width">
    <template slot="header">
      {{ column.title }}
    </template>
    <template slot-scope="{row}">
      {{ row[column.prop] }}
    </template>
    <template v-for="(child, index) in column.columns">
      <component
        :is="'Child'"
        :key="index"
        :column="child">
      </component>
    </template>
  </el-table-column>
</template>

<script>
export default {
  name: 'complex-colunm',
  props: {
    column: {
      type: Object
    }
  },
  beforeCreate () {
    this.$options.components.Child = require('./complexColum1').default
  }
}
</script>

<style lang='less' scoped>
</style>

```

**Comment by Yyc1537** [comment]
好的，我再研究研究

**Comment by xiaocheng555** [comment]
> 好的，我再研究研究

ok，有问题再@我
