### ISSUE TITLE
el-table-virtual-column 中未阻止事件冒泡

### ISSUE THREAD

**Issue by Xy-Zipper** [xiaocheng555/el-table-virtual-scroll#56]
https://github.com/xiaocheng555/el-table-virtual-scroll/blob/d919a46f55ce89e753fa2f5b1b20d6778197a668/src/el-table-virtual-column.vue#L44
element-ui 中的selection 是会阻止默认事件的
![PixPin_2023-12-25_17-07-13](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/54532461/6233effc-ae41-4d3a-80d0-53a7a1d45c14)

**Comment by xiaocheng555** [comment]
> https://github.com/xiaocheng555/el-table-virtual-scroll/blob/d919a46f55ce89e753fa2f5b1b20d6778197a668/src/el-table-virtual-column.vue#L44
> 
> 
> element-ui 中的selection 是会阻止默认事件的
> ![PixPin_2023-12-25_17-07-13](https://private-user-images.githubusercontent.com/54532461/292739136-6233effc-ae41-4d3a-80d0-53a7a1d45c14.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTc0MDIsIm5iZiI6MTcwMzQ5NzEwMiwicGF0aCI6Ii81NDUzMjQ2MS8yOTI3MzkxMzYtNjIzM2VmZmMtYWU0MS00ZDNhLTgwZDAtNTNhN2ExZDQ1YzE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA5MzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Yzk2NjljMTY3ZDk4ZGJkY2ZhOGZmOTAzMTEzNjkxNmY2OTE1NzEzZjc5NzhkNTA4MDY4NjUzOGUwY2E5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MCnHrC3BlqGWNQ2mRHqAtAIwJLDkBxL-pMHFMsiI4cg)



> https://github.com/xiaocheng555/el-table-virtual-scroll/blob/d919a46f55ce89e753fa2f5b1b20d6778197a668/src/el-table-virtual-column.vue#L44
> 
> 
> element-ui 中的selection 是会阻止默认事件的
> ![PixPin_2023-12-25_17-07-13](https://private-user-images.githubusercontent.com/54532461/292739136-6233effc-ae41-4d3a-80d0-53a7a1d45c14.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTc3NjAsIm5iZiI6MTcwMzQ5NzQ2MCwicGF0aCI6Ii81NDUzMjQ2MS8yOTI3MzkxMzYtNjIzM2VmZmMtYWU0MS00ZDNhLTgwZDAtNTNhN2ExZDQ1YzE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA5NDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNDU5OWY0ZTY4YThhZGQ3MDAxODY3MmJjMGE1OTg0MGQ2ZWYxYjUxMDRkNjc4ZmU0YWEwZWY1NjJhNDJlZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ixoye4jWTVEVGqVUmW0Z0KvgWliPxbe2o8MN0IK1Ovw)

代码已经合了，升级到 1.0.32 试试
