### ISSUE TITLE
rowSpanKey 如果存在多个key呢？

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [xiaocheng555/el-table-virtual-scroll#58]

**Comment by xiaocheng555** [comment]
rowSpanKey 是自己造的一个key值，合并行的rowSpanKey是相同的
例如一组合并行为 id: 1, id: 2, id: 3，那么他们的rowSpanKey相同且值可以为gId=1，下一个合并行为gId=2，以此类推，gId 得自己定义

**Comment by xiaocheng555** [comment]
> _No description provided._

**Comment by xiaoxiaohuayu** [comment]
> rowSpanKey 是自己造的一个key值，合并行的rowSpanKey是相同的 例如一组合并行为 id: 1, id: 2, id: 3，那么他们的rowSpanKey相同且值可以为gId=1，下一个合并行为gId=2，以此类推，gId 得自己定义

回复的速度好快😭😭😭。没明白，意思是rowSpanKey是组件自定义的一个key值，如果要多个key是需要在 el-table中span-method 方法中去处理逻辑吗？

**Comment by xiaocheng555** [comment]
> > rowSpanKey 是自己造的一个key值，合并行的rowSpanKey是相同的 例如一组合并行为 id: 1, id: 2, id: 3，那么他们的rowSpanKey相同且值可以为gId=1，下一个合并行为gId=2，以此类推，gId 得自己定义
> 
> 回复的速度好快😭😭😭。没明白，意思是rowSpanKey是组件自定义的一个key值，如果要多个key是需要在 el-table中span-method 方法中去处理逻辑吗？

不太理解你说的多个key是什么，反正是el-table 的span-method 按原来elment-ui定义的来写，rowSpanKey是用告诉虚拟滚动组件哪些行是合并行，如 id: 1, id: 2, id: 3 这三行是合并行，那么这三行的rowSpanKey的值是相同为"g1"；id: 4, id: 5, id: 6 这三行是合并行，那么这三行的rowSpanKey的值是相同为"g2"

**Comment by xiaocheng555** [comment]
你先设置好el-table 的span-method，确定表格能合并行，但是滚动一段距离后，合并行会有问题，此处再去调rowSpanKey

**Comment by xiaocheng555** [comment]
参考这个demo：https://xiaocheng555.github.io/el-table-virtual-scroll/#/Rowspan?code=Rowspan&codeTitle=%E5%90%88%E5%B9%B6%E8%A1%8C

**Comment by xieqx1991** [comment]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/8676463/a1b33419-848b-4621-9c0e-a07fc6bb572b)

多列设置合并行这种情况支持吗

**Comment by xieqx1991** [comment]
哦，可以，:row-span-key 返回数组就行
