### ISSUE TITLE
是否会考虑支持显隐切换后保持滚动条位置

### ISSUE THREAD

**Issue by vjguo** [xiaocheng555/el-table-virtual-scroll#59]
ElTable显隐切换后, 滚动条位置会重置。
但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。
一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置
未来是否会考虑支持这个功能？

**Comment by xiaocheng555** [comment]
> ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？

今晚我搞一下

**Comment by xiaocheng555** [comment]
> ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？

keepalive场景已支持，升级到 1.1.0版本
ElTable显隐切换恢复滚动条方法：
方法1、设置`<el-table :fit="false">`
方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive

**Comment by vjguo** [comment]
> > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> 
> keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive

fit设置为false后 纵向滚动条无法显示了

**Comment by xiaocheng555** [comment]
> > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > 
> > 
> > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> 
> fit设置为false后 纵向滚动条无法显示了

但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧

**Comment by xiaocheng555** [comment]
> > > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > > 
> > > 
> > > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> > 
> > 
> > fit设置为false后 纵向滚动条无法显示了
> 
> 但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧

1.1.1 版本不用手动调restoreScroll方法了

**Comment by vjguo** [comment]
> > > > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > > > 
> > > > 
> > > > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> > > 
> > > 
> > > fit设置为false后 纵向滚动条无法显示了
> > 
> > 
> > 但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧
> 
> 1.1.1 版本不用手动调restoreScroll方法了

1.1.1一级行的没有问题
二级行展开导致应该出滚动条的，滚动条没有了，切换显隐才出现。展开行后已经调用update方法了。
然后好像二级行多的 也不会定位到二级行的位置(非模拟树结构)

**Comment by vjguo** [comment]
> > > > > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > > > > 
> > > > > 
> > > > > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> > > > 
> > > > 
> > > > fit设置为false后 纵向滚动条无法显示了
> > > 
> > > 
> > > 但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧
> > 
> > 
> > 1.1.1 版本不用手动调restoreScroll方法了
> 
> 1.1.1一级行的没有问题 二级行展开导致应该出滚动条的，滚动条没有了，切换显隐才出现。展开行后已经调用update方法了。 然后好像二级行多的 也不会定位到二级行的位置(非模拟树结构)

我这边有一级行少 二级行多的表格，没开启虚拟滚动，有这个现象。

**Comment by vjguo** [comment]
> > > > > > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > > > > > 
> > > > > > 
> > > > > > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> > > > > 
> > > > > 
> > > > > fit设置为false后 纵向滚动条无法显示了
> > > > 
> > > > 
> > > > 但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧
> > > 
> > > 
> > > 1.1.1 版本不用手动调restoreScroll方法了
> > 
> > 
> > 1.1.1一级行的没有问题 二级行展开导致应该出滚动条的，滚动条没有了，切换显隐才出现。展开行后已经调用update方法了。 然后好像二级行多的 也不会定位到二级行的位置(非模拟树结构)
> 
> 我这边有一级行少 二级行多的表格，没开启虚拟滚动，有这个现象。

试了下 是没开启虚拟滚动的原因 是否没开启虚拟滚动 也支持这个功能？

**Comment by xiaocheng555** [comment]
> > > > > > > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > > > > > > 
> > > > > > > 
> > > > > > > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> > > > > > 
> > > > > > 
> > > > > > fit设置为false后 纵向滚动条无法显示了
> > > > > 
> > > > > 
> > > > > 但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧
> > > > 
> > > > 
> > > > 1.1.1 版本不用手动调restoreScroll方法了
> > > 
> > > 
> > > 1.1.1一级行的没有问题 二级行展开导致应该出滚动条的，滚动条没有了，切换显隐才出现。展开行后已经调用update方法了。 然后好像二级行多的 也不会定位到二级行的位置(非模拟树结构)
> > 
> > 
> > 我这边有一级行少 二级行多的表格，没开启虚拟滚动，有这个现象。
> 
> 试了下 是没开启虚拟滚动的原因 是否没开启虚拟滚动 也支持这个功能？

ok，我看看

**Comment by xiaocheng555** [comment]
> > > > > > > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > > > > > > 
> > > > > > > 
> > > > > > > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> > > > > > 
> > > > > > 
> > > > > > fit设置为false后 纵向滚动条无法显示了
> > > > > 
> > > > > 
> > > > > 但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧
> > > > 
> > > > 
> > > > 1.1.1 版本不用手动调restoreScroll方法了
> > > 
> > > 
> > > 1.1.1一级行的没有问题 二级行展开导致应该出滚动条的，滚动条没有了，切换显隐才出现。展开行后已经调用update方法了。 然后好像二级行多的 也不会定位到二级行的位置(非模拟树结构)
> > 
> > 
> > 我这边有一级行少 二级行多的表格，没开启虚拟滚动，有这个现象。
> 
> 试了下 是没开启虚拟滚动的原因 是否没开启虚拟滚动 也支持这个功能？

升级1.1.2试试

**Comment by vjguo** [comment]
> > > > > > > > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> > > > > > > 
> > > > > > > 
> > > > > > > fit设置为false后 纵向滚动条无法显示了
> > > > > > 
> > > > > > 
> > > > > > 但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧
> > > > > 
> > > > > 
> > > > > 1.1.1 版本不用手动调restoreScroll方法了
> > > > 
> > > > 
> > > > 1.1.1一级行的没有问题 二级行展开导致应该出滚动条的，滚动条没有了，切换显隐才出现。展开行后已经调用update方法了。 然后好像二级行多的 也不会定位到二级行的位置(非模拟树结构)
> > > 
> > > 
> > > 我这边有一级行少 二级行多的表格，没开启虚拟滚动，有这个现象。
> > 
> > 
> > 试了下 是没开启虚拟滚动的原因 是否没开启虚拟滚动 也支持这个功能？
> 
> 升级1.1.2试试

展开行还是出不来滚动条。得在expandChange里调用一下nextTick，然后再调用scroll的update方法，才出滚动条。

**Comment by xiaocheng555** [comment]
> > > > > > > > > > ElTable显隐切换后, 滚动条位置会重置。 但类似Tab切换、keepalive等场景，很多时候还是希望能保持滚动条位置的。 一些其他的开源虚拟滚动组件 如vue-virtual-scroller 能够支持保持滚动条位置 未来是否会考虑支持这个功能？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > keepalive场景已支持，升级到 1.1.0版本 ElTable显隐切换恢复滚动条方法： 方法1、设置 方法2、当table切换显示时，手动调用restoreScroll方法，参考案例:https://xiaocheng555.github.io/el-table-virtual-scroll/#/KeepAlive?code=KeepAlive&codeTitle=keep-alive
> > > > > > > > 
> > > > > > > > 
> > > > > > > > fit设置为false后 纵向滚动条无法显示了
> > > > > > > 
> > > > > > > 
> > > > > > > 但就先手动调用restoreScroll方法吧，手动调用restoreScroll好像有点麻烦，我内部处理一下不用手动调吧
> > > > > > 
> > > > > > 
> > > > > > 1.1.1 版本不用手动调restoreScroll方法了
> > > > > 
> > > > > 
> > > > > 1.1.1一级行的没有问题 二级行展开导致应该出滚动条的，滚动条没有了，切换显隐才出现。展开行后已经调用update方法了。 然后好像二级行多的 也不会定位到二级行的位置(非模拟树结构)
> > > > 
> > > > 
> > > > 我这边有一级行少 二级行多的表格，没开启虚拟滚动，有这个现象。
> > > 
> > > 
> > > 试了下 是没开启虚拟滚动的原因 是否没开启虚拟滚动 也支持这个功能？
> > 
> > 
> > 升级1.1.2试试
> 
> 展开行还是出不来滚动条。得在expandChange里调用一下nextTick，然后再调用scroll的update方法，才出滚动条。

没复现出来，有demo吗

**Comment by vjguo** [comment]
拿在线Demo我改不出来，我这边代码封装太多，提出来暂时也没再现，等我再试试。目前现象是，第一次展开，无滚动条，然后关上重新打开，就有了。另外，切换显隐有闪动，表格会先显示最顶部，然后切到上次滚动条位置。等提取出Demo来我再回复。

**Comment by xiaocheng555** [comment]
> 拿在线Demo我改不出来，我这边代码封装太多，提出来暂时也没再现，等我再试试。目前现象是，第一次展开，无滚动条，然后关上重新打开，就有了。另外，切换显隐有闪动，表格会先显示最顶部，然后切到上次滚动条位置。等提取出Demo来我再回复。

切换显隐有闪动，element-ui 的table组件恢复滚动位置就会这样，没找到更好的方法；我试了将table组件 height 改为 max-height 不会有闪动，组件本身会还原回原来的位置，有个小bug就是滚动到最底部后再切换显隐，滚动位置会有很小的偏差
