### ISSUE TITLE
大佬又来麻烦你了

### ISSUE THREAD

**Issue by LiJunXiao** [xiaocheng555/el-table-virtual-scroll#6]
有个需求是这样的，就是一页500条，然后做一个前端搜索的功能，方便用户去勾选，比如搜索第365条符合用户的搜索条件，直接表格滚动到第365行，然后方便他去做选择。。。这种以什么样的一个思路去做呢？

**Comment by xiaocheng555** [comment]
<img width="944" alt="image" src="https://user-images.githubusercontent.com/19643785/211711220-51fee7ed-03d3-4487-a06f-15a18997448b.png">
调用这个scrollTo方法

> 有个需求是这样的，就是一页500条，然后做一个前端搜索的功能，方便用户去勾选，比如搜索第365条符合用户的搜索条件，直接表格滚动到第365行，然后方便他去做选择。。。这种以什么样的一个思路去做呢？

**Comment by xiaocheng555** [comment]
> 有个需求是这样的，就是一页500条，然后做一个前端搜索的功能，方便用户去勾选，比如搜索第365条符合用户的搜索条件，直接表格滚动到第365行，然后方便他去做选择。。。这种以什么样的一个思路去做呢？

ok不，ok我就关闭issue了

**Comment by LiJunXiao** [comment]
可以的，麻烦大佬了
