### ISSUE TITLE
序号列 有bug

### ISSUE THREAD

**Issue by leonhu0710** [xiaocheng555/el-table-virtual-scroll#60]
序号列 type="index"  显示序号错误，因此我自己手动生成序号了，当成普通列渲染；

**Comment by xiaocheng555** [comment]
> 序号列 type="index" 显示序号错误，因此我自己手动生成序号了，当成普通列渲染；

https://xiaocheng555.github.io/el-table-virtual-scroll/#/VIndex?code=VIndex&codeTitle=%E7%B4%A2%E5%BC%95

![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/5cd8c49f-7148-4ae4-8658-8810464841cb)
看demo，是正常的

**Comment by xiaocheng555** [comment]
没有问题，我就关issue了
