### ISSUE TITLE
el-table 中包含  行合并单元格 时，样式滚动时 表格左右错乱

### ISSUE THREAD

**Issue by leonhu0710** [xiaocheng555/el-table-virtual-scroll#61]
el-table 中包含  行合并单元格 时，样式滚动时 表格左右错乱

**Comment by xiaocheng555** [comment]
> el-table 中包含 行合并单元格 时，样式滚动时 表格左右错乱

https://xiaocheng555.github.io/el-table-virtual-scroll/#/Rowspan?code=Rowspan&codeTitle=%E5%90%88%E5%B9%B6%E8%A1%8C

需要设置row-span-key的值

**Comment by leonhu0710** [comment]
我使用的这个组件，用了合并行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月12日(周五) 晚上6:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaocheng555/el-table-virtual-scroll] el-table 中包含  行合并单元格 时，样式滚动时 表格左右错乱 (Issue #61)




  
el-table 中包含 行合并单元格 时，样式滚动时 表格左右错乱
  
https://xiaocheng555.github.io/el-table-virtual-scroll/#/Rowspan?code=Rowspan&amp;codeTitle=%E5%90%88%E5%B9%B6%E8%A1%8C
 
需要设置row-span-key的值

**Comment by leonhu0710** [comment]
谢谢大佬，我再研究下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月12日(周五) 晚上6:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaocheng555/el-table-virtual-scroll] el-table 中包含  行合并单元格 时，样式滚动时 表格左右错乱 (Issue #61)




  
el-table 中包含 行合并单元格 时，样式滚动时 表格左右错乱
  
https://xiaocheng555.github.io/el-table-virtual-scroll/#/Rowspan?code=Rowspan&amp;codeTitle=%E5%90%88%E5%B9%B6%E8%A1%8C
 
需要设置row-span-key的值

**Comment by xiaocheng555** [comment]
没有问题，我就关issue了

**Comment by leonhu0710** [comment]
没有问题，辛苦大佬跟踪排查



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 晚上6:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaocheng555/el-table-virtual-scroll] el-table 中包含  行合并单元格 时，样式滚动时 表格左右错乱 (Issue #61)




 
没有问题，我就关issue了
