### ISSUE TITLE
多选 - 源码案例拷贝下来， 一直报错id重复

### ISSUE THREAD

**Issue by jipengju-GitHub** [xiaocheng555/el-table-virtual-scroll#62]
"el-table-virtual-scroll": "^1.1.2",
"element-ui": "^2.13.2",
"vue": "2.7.14",

报错现象：
拷贝案例代码报错， 鼠标滚动时持续相同报错

报错提示：
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/47650295/cfb2b7c7-61a4-4774-96c6-6c3badef1edb)

代码：
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/47650295/b66ebdf0-6acb-45c8-9ae1-a7e35b611daa)

**Comment by xiaocheng555** [comment]
> "el-table-virtual-scroll": "^1.1.2", "element-ui": "^2.13.2", "vue": "2.7.14",
> 
> 报错现象： 拷贝案例代码报错， 鼠标滚动时持续相同报错
> 
> 报错提示： ![image](https://private-user-images.githubusercontent.com/47650295/296720114-cfb2b7c7-61a4-4774-96c6-6c3badef1edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTYxODcsIm5iZiI6MTcwNTMxNTg4NywicGF0aCI6Ii80NzY1MDI5NS8yOTY3MjAxMTQtY2ZiMmI3YzctNjFhNC00Nzc0LTk2YzYtNmMzYmFkZWYxZWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwNTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OTMzZDNlNDRhNDcxYTg5YTUxMTFmMjQ1MDJiMzJlYjRmMGY0MzM3ZjRmYmFkZjkxNjQ3NTc3OTA1ZDIyNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2_-XFL91PaQXLQixASPhwDYAOkpJhmQyAIako4V4ArE)
> 
> 代码： ![image](https://private-user-images.githubusercontent.com/47650295/296719652-b66ebdf0-6acb-45c8-9ae1-a7e35b611daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTYxODcsIm5iZiI6MTcwNTMxNTg4NywicGF0aCI6Ii80NzY1MDI5NS8yOTY3MTk2NTItYjY2ZWJkZjAtNmFjYi00NWM4LTlhZTEtYTdlMzViNjExZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwNTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNTQ2OGY0OTVjYjk2OTJkM2JlMTE3Y2QzMzhhMmE1OWZhMGNmNTUyNTFmOGRmYzc3Zjk4ZTE2ZGVjYTczNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XSdSDd9m-DUWmHlJFicqhtHIx5-B9WrTS04WAKZnDWY)

传入的表格数据里面没有id或者id都一样，key-prop需要是唯一值
