### ISSUE TITLE
帮忙回答下:   初始化数据的方法一定要在created里面调用吗?  我现在想做导入后虚拟滚动渲染 显示数据都是重复的 

### ISSUE THREAD

**Issue by yinxuejing123** [xiaocheng555/el-table-virtual-scroll#64]
导入后如何初始化表格数据  现在 导入后给
<virtual-scroll :data="virtualData" ref="virtualScroll" :item-size="62" key-prop="id" @change="changeData">
            <el-table :data="editForm.diaTableData" row-key="id" :loadingt="loadingt" tooltip-effect="dark" style="width: 100%" height="350px" :header-cell-style="{background:'#F5F6FA',fontWeight: 700}" :key="formIndex"> virtualData赋值  但列表每次滚动时数据一直被前几条覆盖

**Comment by yinxuejing123** [comment]
![微信图片_20240118144241](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/31094777/2fdcb8b5-255d-45b7-9bbc-a97eec4514a0)
这是导入Excel 成功后初始化方法的代码   
changeData(renderData){
      this.editForm.diaTableData = renderData
    },   这是change时候的代码

**Comment by xiaocheng555** [comment]
> 导入后如何初始化表格数据 现在 导入后给 <virtual-scroll :data="virtualData" ref="virtualScroll" :item-size="62" key-prop="id" @change="changeData"> virtualData赋值 但列表每次滚动时数据一直被前几条覆盖

不用在created里面调用，你这样写应该是可以的，有没有其他报错吗

**Comment by yinxuejing123** [comment]
没有报错 现在就是拿到数据后页面数据会重复
![微信图片_20240118171556](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/31094777/02a70b23-b5b1-47a3-ae0c-5c8875aa2baa)
然后wok我看你的demo 列表滚动的时候 红色部分都在动   我的只是第一个transform: translateY(1215px);在动  然后展示的就不对了 我导入的是20条数据  页面滚动到底部就变成了28条

**Comment by xiaocheng555** [comment]
> 没有报错 现在就是拿到数据后页面数据会重复 ![微信图片_20240118171556](https://private-user-images.githubusercontent.com/31094777/297686692-02a70b23-b5b1-47a3-ae0c-5c8875aa2baa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzIwMDMsIm5iZiI6MTcwNTU3MTcwMywicGF0aCI6Ii8zMTA5NDc3Ny8yOTc2ODY2OTItMDJhNzBiMjMtYjViMS00N2EzLWFlMGMtNWM4ODc1YWEyYmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA5NTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NDZiOGU5OWQ1OTIwZTBmOWFkOGJiMjA4ZmY1ZjI4MWQ3NjMxOWIxMGI1NGZkNjhiOWUwNDkzODllZWFmNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3mMRAkezm4K7Y7tQ7g9M5RfOACaOIobZ7QMbFQWMhfs) 然后wok我看你的demo 列表滚动的时候 红色部分都在动 我的只是第一个transform: translateY(1215px);在动 然后展示的就不对了 我导入的是20条数据 页面滚动到底部就变成了28条
`<el-table>` 的代码贴出来看下

**Comment by xiaocheng555** [comment]
`<el-table>` 的代码贴出来看下，或者有没有demo

**Comment by xiaocheng555** [comment]
> `<el-table>` 的代码贴出来看下，或者有没有demo

key-prop="id" 里面的id是唯一值吗

**Comment by yinxuejing123** [comment]
是唯一的  是以导入后遍历数据的索引作为唯一值的
  <virtual-scroll :data="virtualData" ref="virtualScroll" :item-size="62" key-prop="id" @change="changeData">
            <el-table :data="editForm.diaTableData" row-key="id" :loadingt="loadingt" tooltip-effect="dark" style="width: 100%" height="350px" :header-cell-style="{background:'#F5F6FA',fontWeight: 700}" :key="formIndex">
              <virtual-column type="index" width="50" label="序号"></virtual-column>
![Uploading 微信图片_20240119092519.png…]()

**Comment by yinxuejing123** [comment]
![微信图片_20240119092519](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/31094777/6cac4b33-de3e-4a13-bf3c-273c465e3c18)

**Comment by xiaocheng555** [comment]
> ![微信图片_20240119092519](https://private-user-images.githubusercontent.com/31094777/297924864-6cac4b33-de3e-4a13-bf3c-273c465e3c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Mjc5MzksIm5iZiI6MTcwNTYyNzYzOSwicGF0aCI6Ii8zMTA5NDc3Ny8yOTc5MjQ4NjQtNmNhYzRiMzMtZGUzZS00YTEzLWJmM2MtMjczYzQ2NWUzYzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAxMjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MTU2ZWNlOTYyZjA5NWJlMmIyMmJlMzdmYmZmZWZkY2UxZTcwMjRiMTFlOWIyMWYyNzNkYWE3ZTY4NDJmZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4RQa_9kCBLQhVX2qK2sB7kt8kDWUBsnHdvvwt1zuOKo)

删点el-table的key试试，或者将key放在 virtual-scroll

**Comment by yinxuejing123** [comment]
去掉key 或者放在virtual-scroll 还是一样

**Comment by yinxuejing123** [comment]
![微信图片_20240119112238](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/31094777/562b4930-9e30-4079-927d-43106b683e2f)
这是我的列表  跟里面嵌套el-input  el-select el-popover 这些没关系吧

**Comment by xiaocheng555** [comment]
> ![微信图片_20240119112238](https://private-user-images.githubusercontent.com/31094777/297944047-562b4930-9e30-4079-927d-43106b683e2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzUyMjUsIm5iZiI6MTcwNTYzNDkyNSwicGF0aCI6Ii8zMTA5NDc3Ny8yOTc5NDQwNDctNTYyYjQ5MzAtOWUzMC00MDc5LTkyN2QtNDMxMDZiNjgzZTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyOTRmMzIzNDhmNjc2MTNmYjEwNjFhMDE5YzBkZTMzY2VmNzk4MzJlN2I5ZjE2NGQzOTcyNmVjYTQxMzEwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._1_GF9zeYVA0usb3WjZdqAlAg7skNhqMW5o4ItyCKRc) 这是我的列表 跟里面嵌套el-input el-select el-popover 这些没关系吧

最好有个demo吧，肉眼看不出什么问题

**Comment by yinxuejing123** [comment]
找到原因了  就是我el-form 嵌套了<virtual-scroll :data="virtualData" ref="virtualScroll" :item-size="30" key-prop="id" @change="changeData">
            <el-table
              :data="diaTableData"
              row-key="id"
              :loadingt="loadingt"
              tooltip-effect="dark"
              style="width: 100%"
              height="100px"
              :header-cell-style="{background:'#F5F6FA',fontWeight: 700}"
            >
              <virtual-column type="index" width="50" label="序号"></virtual-column>
              <el-table-column prop="itemcode" label="物料代码" min-width="100">
                <template slot-scope="scope">
                  <el-form-item prop="itemcode" :rules="{ required: true, message: '物料代码不能为空', trigger: 'change' }">
                    <el-select size="medium"  v-model="scope.row.itemcode" placeholder="请选择物料组" clearable filterable disabled>
                      <el-option
                        v-for="item in itemcodes"
                        :key="item.code"
                        :label="item.name"
                        :value="item.code+''">
                      </el-option>
                    </el-select>
                  </el-form-item>
                </template>
              </el-table-column>
              <el-table-column prop="itemcode" label="物料代码2" min-width="100"></el-table-column>
              <el-table-column prop="itemrelation" label="物料代码3" min-width="100"></el-table-column>
              <el-table-column prop="itemcode" label="物料代码4" min-width="100"></el-table-column>
              <el-table-column prop="accountcode" label="物料代码5" min-width="100"></el-table-column>
              <el-table-column prop="itemcode" label="物料代码6" min-width="100"></el-table-column>
              <el-table-column prop="itemrelation" label="物料代码7" min-width="100"></el-table-column>
              <el-table-column prop="accountcode" label="物料代码8" min-width="100"></el-table-column>
              <el-table-column prop="itemcode" label="物料代码9" min-width="100"></el-table-column>
              <el-table-column prop="itemrelation" label="物料代码10" min-width="100"></el-table-column>
              <el-table-column prop="itemcode" label="物料代码11" min-width="100"></el-table-column>
              <el-table-column prop="itemcode" label="物料代码" min-width="100">
                <template slot-scope="scope">
                  <el-form-item :prop=" 'diaTableData.' + scope.$index + '.itemcode' " :rules="{ required: true, message: '物料代码不能为空', trigger: 'change' }">
                    <el-select size="medium"  v-model="scope.row.itemcode" placeholder="请选择物料组" clearable filterable disabled>
                      <el-option
                        v-for="item in itemcodes"
                        :key="item.code"
                        :label="item.name"
                        :value="item.code+''">
                      </el-option>
                    </el-select>
                  </el-form-item>
                </template>
              </el-table-column>  :prop=" 'diaTableData.' + scope.$index + '.itemcode' "   这么写就会出现重复的问题  直接绑定prop就跟你demo一样了   这个有办法解决吗?

**Comment by yinxuejing123** [comment]
是因为scope.$index 现在不是每一行正确的索引了?

**Comment by xiaocheng555** [comment]
> 是因为scope.$index 现在不是每一行正确的索引了?

是的，scope.$index 不是正确的索引，需要加上前面未渲染数据的索引值，例如：
@change="changeData"
changeData (renderData, start) { this.start = start }

真正的索引是：$index + this.start

**Comment by yinxuejing123** [comment]
找到的原因是el-form 嵌套了virtual-scroll  el-table的data 绑定的是 :data="editForm.dialogTableData"  改变data的绑定值就显示正常了
 <virtual-scroll :data="virtualData" ref="virtualScroll" :item-size="30" key-prop="id" @change="changeData">
            <el-table
              :data="editForm.dialogTableData"
              row-key="id"
              :loadingt="loadingt"
              tooltip-effect="dark"
              style="width: 100%"
              height="100px"
              :header-cell-style="{background:'#F5F6FA',fontWeight: 700}"
            >
              <virtual-column type="index" width="50" label="序号"></virtual-column>
              <el-table-column prop="itemcode" label="物料代码" min-width="100">
                <template slot-scope="scope">
                  <el-form-item prop="itemcode" :rules="{ required: true, message: '物料代码不能为空', trigger: 'change' }">
                    <el-select size="medium"  v-model="scope.row.itemcode" placeholder="请选择物料组" clearable filterable disabled>
                      <el-option
                        v-for="item in itemcodes"
                        :key="item.code"
                        :label="item.name"
                        :value="item.code+''">
                      </el-option>
                    </el-select>
                  </el-form-item>
                </template>
              </el-table-column>

**Comment by yinxuejing123** [comment]
![微信图片_20240120151807](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/31094777/99efcb9d-c19b-4dc3-93d2-9d330dc7a501)
这是我的代码  只要改掉el-table绑定的值(非el-form中的)就可以了 但是我需要表格中设置校验  这怎么处理?

**Comment by xiaocheng555** [comment]
> ![微信图片_20240120151807](https://private-user-images.githubusercontent.com/31094777/298267987-99efcb9d-c19b-4dc3-93d2-9d330dc7a501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Mzc1NTEsIm5iZiI6MTcwNTczNzI1MSwicGF0aCI6Ii8zMTA5NDc3Ny8yOTgyNjc5ODctOTllZmNiOWQtYzE5Yi00ZGMzLTkzZDItOWQzMzBkYzdhNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA3NTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYmE4MTIxZDA0YzkwZTg2NWFkYWRkMmI2Njg0ODk1Yzc0NzI5ZmZmNDU5MmVjNWY0ODFmZmQzZjUxMWQ5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.epTMoWw2l9OsEaYHPQCHXnf1qO6vXKBp4zSZ7J6mSeE) 这是我的代码 只要改掉el-table绑定的值(非el-form中的)就可以了 但是我需要表格中设置校验 这怎么处理?

虚拟滚动用不了el-form做校验，因为每次滚动，都会把前面的校验给销毁掉，而且没有渲染的行是校验不了，可能得自己写校验逻辑

**Comment by yinxuejing123** [comment]
好的 了解了 谢谢
