### ISSUE TITLE
更新到1.1.3后报错 el-table-column未注册

### ISSUE THREAD

**Issue by vjguo** [xiaocheng555/el-table-virtual-scroll#66]
之前使用按需引入的方式，更到1.1.3后，报错。

**Comment by xiaocheng555** [comment]
> 之前使用按需引入的方式，更到1.1.3后，报错。

可能修复之前一个bug导致的，我看看

**Comment by xiaocheng555** [comment]
> 之前使用按需引入的方式，更到1.1.3后，报错。
按需引入的方式 是怎么引入，有代码吗

**Comment by vjguo** [comment]
> 之前使用按需引入的方式，更到1.1.3后，报错。
> 按需引入的方式 是怎么引入，有代码吗

就不通过那个插件，跟之前版本VirtualColumn引入方式一样，直接从element-ui包import的。

**Comment by xiaocheng555** [comment]
> > 之前使用按需引入的方式，更到1.1.3后，报错。
> > 按需引入的方式 是怎么引入，有代码吗
> 
> 就不通过那个插件，跟之前版本VirtualColumn引入方式一样，直接从element-ui包import的。

没明白什么意思，同时我也复现不出来

**Comment by vjguo** [comment]
可能是我说的不太清楚，我换个表述方式。我的项目只通过npm i安装element依赖，项目不会引入任何element的东西。没有按需引入或者全局引入的事。 之前VirtualColumn代码里有import语句 现在移除了，我怀疑是这个原因。

**Comment by vjguo** [comment]
可能是我说的不太清楚，我换个表述方式。我的项目只通过npm i安装element依赖，项目不会引入任何element的东西。没有按需引入或者全局引入的事。 之前VirtualColumn代码里有import语句 现在移除了，我怀疑是这个原因。

**Comment by xiaocheng555** [comment]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/394dd276-47ed-404f-a6e8-2b33775bd2fa)
改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题

**Comment by vjguo** [comment]
> 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题

这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……

**Comment by xiaocheng555** [comment]
> > 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题
> 
> 这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……

我demo里可以，我改为import发个版试试，可能晚点，现在一直发版不成功

**Comment by vjguo** [comment]
> 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题

这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……

**Comment by vjguo** [comment]
> > > 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题
> > 
> > 
> > 这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……
> 
> 我demo里可以，我改为import发个版试试，可能晚点，现在一直发版不成功

好 我也再看看 可能和我是Electron环境有关

**Comment by xiaocheng555** [comment]
> > > > 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题
> > > 
> > > 
> > > 这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……
> > 
> > 
> > 我demo里可以，我改为import发个版试试，可能晚点，现在一直发版不成功
> 
> 好 我也再看看 可能和我是Electron环境有关

升级到1.1.4看看，改为import了

**Comment by vjguo** [comment]
> > > > > 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题
> > > > 
> > > > 
> > > > 这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……
> > > 
> > > 
> > > 我demo里可以，我改为import发个版试试，可能晚点，现在一直发版不成功
> > 
> > 
> > 好 我也再看看 可能和我是Electron环境有关
> 
> 升级到1.1.4看看，改为import了

我又检查了下代码，我手动给Vue原型赋过$ELEMENT变量，为的是按需引入，组件也能获取全局设置，比如大小zindex。 我删掉我的设置，目前1.1.4是好使的。 能否评估一下是否允许开发者手动赋这个变量，考虑别的方式来判断是否全局引入？ 比如直接判断是否全局注册了ElTableColumn组件，名字必须匹配不能改名，我觉得这样更直接也更准确。

**Comment by xiaocheng555** [comment]
> > > > > > 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题
> > > > > 
> > > > > 
> > > > > 这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……
> > > > 
> > > > 
> > > > 我demo里可以，我改为import发个版试试，可能晚点，现在一直发版不成功
> > > 
> > > 
> > > 好 我也再看看 可能和我是Electron环境有关
> > 
> > 
> > 升级到1.1.4看看，改为import了
> 
> 我又检查了下代码，我手动给Vue原型赋过$ELEMENT变量，为的是按需引入，组件也能获取全局设置，比如大小zindex。 我删掉我的设置，目前1.1.4是好使的。 能否评估一下是否允许开发者手动赋这个变量，考虑别的方式来判断是否全局引入？ 比如直接判断是否全局注册了ElTableColumn组件，名字必须匹配不能改名，我觉得这样更直接也更准确。

ok，我直接判断是否全局注册了ElTableColumn组件吧

**Comment by xiaocheng555** [comment]
> > > > > > 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题
> > > > > 
> > > > > 
> > > > > 这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……
> > > > 
> > > > 
> > > > 我demo里可以，我改为import发个版试试，可能晚点，现在一直发版不成功
> > > 
> > > 
> > > 好 我也再看看 可能和我是Electron环境有关
> > 
> > 
> > 升级到1.1.4看看，改为import了
> 
> 我又检查了下代码，我手动给Vue原型赋过$ELEMENT变量，为的是按需引入，组件也能获取全局设置，比如大小zindex。 我删掉我的设置，目前1.1.4是好使的。 能否评估一下是否允许开发者手动赋这个变量，考虑别的方式来判断是否全局引入？ 比如直接判断是否全局注册了ElTableColumn组件，名字必须匹配不能改名，我觉得这样更直接也更准确。

1.1.5 修复了，试下

**Comment by vjguo** [comment]
> > > > > > > 改为require 引入了，全局引入element-ui会有 this.$ELEMENT 这个变量，非全局引入的话会require去引入对应组件，难道是require的问题
> > > > > > 
> > > > > > 
> > > > > > 这样require编译的时候应该不会加到依赖图里吧…… 应该只有node环境可以……
> > > > > 
> > > > > 
> > > > > 我demo里可以，我改为import发个版试试，可能晚点，现在一直发版不成功
> > > > 
> > > > 
> > > > 好 我也再看看 可能和我是Electron环境有关
> > > 
> > > 
> > > 升级到1.1.4看看，改为import了
> > 
> > 
> > 我又检查了下代码，我手动给Vue原型赋过$ELEMENT变量，为的是按需引入，组件也能获取全局设置，比如大小zindex。 我删掉我的设置，目前1.1.4是好使的。 能否评估一下是否允许开发者手动赋这个变量，考虑别的方式来判断是否全局引入？ 比如直接判断是否全局注册了ElTableColumn组件，名字必须匹配不能改名，我觉得这样更直接也更准确。
> 
> 1.1.5 修复了，试下

1.1.5没问题了
