### ISSUE TITLE
大佬，selection-change 返回的选中行能不能按照勾选的先后顺序啊

### ISSUE THREAD

**Issue by LiJunXiao** [xiaocheng555/el-table-virtual-scroll#7]
比如我先选第二行，再选第一行，那么返回的数组的第一个元素就是第二行，第二个元素就是第一行。现在是会按照固定的一个顺序来返回吧？并不是按照勾选的先后顺序。

**Comment by xiaocheng555** [comment]
> 比如我先选第二行，再选第一行，那么返回的数组的第一个元素就是第二行，第二个元素就是第一行。现在是会按照固定的一个顺序来返回吧？并不是按照勾选的先后顺序。

确实，我改一下

**Comment by xiaocheng555** [comment]
> 比如我先选第二行，再选第一行，那么返回的数组的第一个元素就是第二行，第二个元素就是第一行。现在是会按照固定的一个顺序来返回吧？并不是按照勾选的先后顺序。


修复了，升级一下el-table-virtual-scroll@1.0.4：npm i el-table-virtual-scroll@1.0.4 -S

**Comment by xiaocheng555** [comment]
> 比如我先选第二行，再选第一行，那么返回的数组的第一个元素就是第二行，第二个元素就是第一行。现在是会按照固定的一个顺序来返回吧？并不是按照勾选的先后顺序。

1.0.4 发错包了😂，需要升级一下el-table-virtual-scroll@1.0.5：npm i el-table-virtual-scroll@1.0.5 -S
