### ISSUE TITLE
使用toggleRowSelection选中多行会卡死，有什么办法高效选中多行么

### ISSUE THREAD

**Issue by cug-zgj** [xiaocheng555/el-table-virtual-scroll#73]

**Comment by xiaocheng555** [comment]
例如：设置第一行为选中：this.list[1].set('$v_checked', true)

**Comment by cug-zgj** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月25日(星期一) 上午9:53
收件人: ***@***.***&gt;; 
抄送: "Unlimited Blade ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaocheng555/el-table-virtual-scroll] 使用toggleRowSelection选中多行会卡死，有什么办法高效选中多行么 (Issue #73)





 
例如：设置第一行为选中：this.list[1].set('$v_checked', true)

**Comment by xiaocheng555** [comment]
我优化一下吧，toggleRowSelection方法可以传数组，this.$refs.virtualScroll.toggleRowSelection(row,  true) 这样，晚点发个版

**Comment by xiaocheng555** [comment]
> _No description provided._

升级版本到 1.1.8，toggleRowSelection方法支持传入数组，this.$refs.virtualScroll.toggleRowSelection(rows, true)

**Comment by xiaocheng555** [comment]
> _No description provided._

问题解决了吗

**Comment by cug-zgj** [comment]
问题解决了，感谢开发者的及时更新
