### ISSUE TITLE
新增 Backtop 回到顶部 功能

### ISSUE THREAD

**Issue by yize-dev** [xiaocheng555/el-table-virtual-scroll#74]
新增 Backtop 回到顶部 功能

**Comment by xiaocheng555** [comment]
<img width="965" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/364907b8-067f-41f0-a7c9-1f1a751f7450">
xxx.scscrollTo(0) 用这个方法
