### ISSUE TITLE
希望支持横向滚动条sticky

### ISSUE THREAD

**Issue by WebEngineerLi** [xiaocheng555/el-table-virtual-scroll#78]
表格没有滚动到底部时横向滚动条被遮挡，希望可以支持横向滚动条 sticky

![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/30517805/e7a58d14-45a2-44c2-ba56-eb4d5e2d4322)

**Comment by xiaocheng555** [comment]
> 表格没有滚动到底部时横向滚动条被遮挡，希望可以支持横向滚动条 sticky
> 
> ![image](https://private-user-images.githubusercontent.com/30517805/321283506-e7a58d14-45a2-44c2-ba56-eb4d5e2d4322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTkyMzAsIm5iZiI6MTcxMjc5ODkzMCwicGF0aCI6Ii8zMDUxNzgwNS8zMjEyODM1MDYtZTdhNThkMTQtNDVhMi00NGMyLWJhNTYtZWI0ZDVlMmQ0MzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAxMjg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZmMyMjBiN2MyYmM4ZDAzOWE2M2Q5YzdhOGVkYTViNmZiZDZjNTk1NjVlNWY1YmNmMzQzNTViYjA3ZjcyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XErBoHaTMT41TIyff9thNaE5ATIYy89j8PrdfaropCc)

要横向滚动条的话只能固定表格高度；如果表格不固定高度的话滚动条只会显示在底部，这是浏览器合理行为，组件不做支持

**Comment by WebEngineerLi** [comment]
> > 表格没有滚动到底部时横向滚动条被遮挡，希望可以支持横向滚动条 sticky
> > ![image](https://private-user-images.githubusercontent.com/30517805/321283506-e7a58d14-45a2-44c2-ba56-eb4d5e2d4322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTkyMzAsIm5iZiI6MTcxMjc5ODkzMCwicGF0aCI6Ii8zMDUxNzgwNS8zMjEyODM1MDYtZTdhNThkMTQtNDVhMi00NGMyLWJhNTYtZWI0ZDVlMmQ0MzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDAxMjg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZmMyMjBiN2MyYmM4ZDAzOWE2M2Q5YzdhOGVkYTViNmZiZDZjNTk1NjVlNWY1YmNmMzQzNTViYjA3ZjcyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XErBoHaTMT41TIyff9thNaE5ATIYy89j8PrdfaropCc)
> 
> 要横向滚动条的话只能固定表格高度；如果表格不固定高度的话滚动条只会显示在底部，这是浏览器合理行为，组件不做支持

这种也算是比较常见的场景吧，当表格滚动容器为 window 的时候，如果是鼠标用户要滑到底部才能横向滚动，体验确实不好。
这种 case 下，可以用代码自定义一个横向滚动条 sticky 滚动容器的底部，然后和表格的横向滚动做联动就好了。或者组件可以开放一个slot出来，让开发者自定义横向滚动条，组件只负责渲染。

**Comment by xiaocheng555** [comment]
```
<virtual-scroll>
  <el-table />
  <div>滚动条</div>
</virtual-scroll>
```
可以这样子写，不知道满足你的需求不

**Comment by WebEngineerLi** [comment]
> ```
> <virtual-scroll>
>   <el-table />
>   <div>滚动条</div>
> </virtual-scroll>
> ```
> 
> 可以这样子写，不知道满足你的需求不

可以的
