### ISSUE TITLE
关于在resize后vfixed类名错误问题

### ISSUE THREAD

**Issue by izhl-2023** [xiaocheng555/el-table-virtual-scroll#79]
先在小窗口模式出现横向滚动条后，拖动到最右边，最大化窗口后在窗口化回到之前的小窗口后，在这个类名类名.el-table>.el-table__body-wrapper.is-scrolling-right 里面的‘is-scrolling-right’是错误的，此时应该是‘is-scrolling-left’
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/83797961/ab6c8de2-5575-4b79-ae20-2a48bc26e2da)
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/83797961/586e2ead-97ff-44c9-a5cf-241fbf515dc3)
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/83797961/c7b8409b-7c1a-414d-88c7-ea05579ae3a4)

重新滚动后，样式计算恢复正常

**Comment by xiaocheng555** [comment]
已修复，升级到1.1.10
