### ISSUE TITLE
1.0.6报错了

### ISSUE THREAD

**Issue by 593496637** [xiaocheng555/el-table-virtual-scroll#8]

**Comment by 593496637** [comment]
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/15769004/212083128-7010118f-9fc2-4901-897d-dcd01009848b.png">

**Comment by xiaocheng555** [comment]
可能是<el-table-virtual-column> 组件内部引入table-column 方式不对，你试试升级到el-table-virtual-scroll@1.0.7看看能不能解决

**Comment by xiaocheng555** [comment]
> 可能是 组件内部引入table-column 方式不对，你试试升级到el-table-virtual-scroll@1.0.7看看能不能解决

**Comment by xiaocheng555** [comment]
> <img alt="image" width="1057" src="https://user-images.githubusercontent.com/15769004/212083128-7010118f-9fc2-4901-897d-dcd01009848b.png">

可能是 `<el-table-virtual-column>` 组件内部引入table-column 方式不对，你试试升级到el-table-virtual-scroll@1.0.7看看能不能解决

**Comment by 593496637** [comment]
问题没有了

**Comment by xiaocheng555** [comment]
> 问题没有了

👌
