### ISSUE TITLE
虚拟表格如果动态添加数据的时候就会出现空白，主要是产生的偏移值不对

### ISSUE THREAD

**Issue by keep1224** [xiaocheng555/el-table-virtual-scroll#80]

**Comment by xiaocheng555** [comment]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/19643785/06b12452-6a60-460b-bf83-8fd8f639e6d6)
调用这个方法

**Comment by xiaocheng555** [comment]
> _No description provided._

解决了吗
