### ISSUE TITLE
this.elTable.syncPosition is not a function

### ISSUE THREAD

**Issue by Fadeoc** [xiaocheng555/el-table-virtual-scroll#82]
![屏幕截图 2024-04-23 173846](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/8510013/041beda6-1bb4-41bb-85bd-441449b194b1)

elTable并没有syncPosition 这个方法，是element-ui的版本不对吗

**Comment by xiaocheng555** [comment]
element-ui 哪个版本，el-table 组件有syncPosition这个方法吗

**Comment by xiaocheng555** [comment]
> ![屏幕截图 2024-04-23 173846](https://private-user-images.githubusercontent.com/8510013/324779878-041beda6-1bb4-41bb-85bd-441449b194b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Njg3NDEsIm5iZiI6MTcxMzg2ODQ0MSwicGF0aCI6Ii84NTEwMDEzLzMyNDc3OTg3OC0wNDFiZWRhNi0xYmI0LTQxYmItODViZC00NDE0NDliMTk0YjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTAzNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlhN2ZhYzRjZTY1NTgzMTYxNTJjNmIzODU2N2FjOGJlNDBhNjVhNzdjYWIwZTY3ZDIzOWEwZTJjNmI5MmY1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2AwsGB33QVWNpWQJaC1FVWFLAycNVnwU3Lg4L9sV2vo)
> 
> elTable并没有syncPosition 这个方法，是element-ui的版本不对吗

升级到1.1.12，做了兼容，不存在syncPosition就不报错

**Comment by Fadeoc** [comment]
> > ![屏幕截图 2024-04-23 173846](https://private-user-images.githubusercontent.com/8510013/324779878-041beda6-1bb4-41bb-85bd-441449b194b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Njg3NDEsIm5iZiI6MTcxMzg2ODQ0MSwicGF0aCI6Ii84NTEwMDEzLzMyNDc3OTg3OC0wNDFiZWRhNi0xYmI0LTQxYmItODViZC00NDE0NDliMTk0YjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTAzNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlhN2ZhYzRjZTY1NTgzMTYxNTJjNmIzODU2N2FjOGJlNDBhNjVhNzdjYWIwZTY3ZDIzOWEwZTJjNmI5MmY1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2AwsGB33QVWNpWQJaC1FVWFLAycNVnwU3Lg4L9sV2vo)
> > elTable并没有syncPosition 这个方法，是element-ui的版本不对吗
> 
> 升级到1.1.12，做了兼容，不存在syncPosition就不报错

可以用了，谢谢
