### ISSUE TITLE
虚拟列表是否有类似el-table实例中的selection属性

### ISSUE THREAD

**Issue by Heart110** [xiaocheng555/el-table-virtual-scroll#86]

**Comment by xiaocheng555** [comment]
> _No description provided._

selection是指多选？

**Comment by Heart110** [comment]
> > _No description provided._
> 
> selection是指多选？

是的，有需要通过$refs外部获取selection的场景

**Comment by xiaocheng555** [comment]
> > > _No description provided._
> > 
> > 
> > selection是指多选？
> 
> 是的，有需要通过$refs外部获取selection的场景

没理解

**Comment by xiaocheng555** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > selection是指多选？
> > > 
> > > 
> > > 是的，有需要通过$refs外部获取selection的场景
> > 
> > 
> > 没理解
> > 能不能通过$ref获取到已选中的行

没有，要通过监听选中事件

**Comment by Heart110** [comment]
> > > > > > _No description provided._
> > > > > 
> > > > > 
> > > > > selection是指多选？
> > > > 
> > > > 
> > > > 是的，有需要通过$refs外部获取selection的场景
> > > 
> > > 
> > > 没理解
> > > 能不能通过$ref获取到已选中的行
> 
> 没有，要通过监听选中事件

selection-change事件么

**Comment by xiaocheng555** [comment]
> > > > > > > _No description provided._
> > > > > > 
> > > > > > 
> > > > > > selection是指多选？
> > > > > 
> > > > > 
> > > > > 是的，有需要通过$refs外部获取selection的场景
> > > > 
> > > > 
> > > > 没理解
> > > > 能不能通过$ref获取到已选中的行
> > 
> > 
> > 没有，要通过监听选中事件
> 
> selection-change事件么

https://xiaocheng555.github.io/el-table-virtual-scroll/#/VSelectionDemo?code=VSelectionDemo&codeTitle=%E5%A4%9A%E9%80%89
是的，参考这个demo
