### ISSUE TITLE
vue3 为啥没有更新了？

### ISSUE THREAD

**Issue by sangeren** [xiaocheng555/el-table-virtual-scroll#87]
[el-table-virtual-scroll-next](https://github.com/xiaocheng555/el-table-virtual-scroll-next) 好久没有更新了，是不在维护了吗？、

**Comment by xiaocheng555** [comment]
> [el-table-virtual-scroll-next](https://github.com/xiaocheng555/el-table-virtual-scroll-next) 好久没有更新了，是不在维护了吗？、

看着没什么人用，没有更新的必要
