### ISSUE TITLE
使用模拟树结构懒加载时，如何让prop不显示

### ISSUE THREAD

**Issue by cug-zgj** [xiaocheng555/el-table-virtual-scroll#88]

**Comment by cug-zgj** [comment]
仍然有prop，但是具体是什么不显示在virtual-column那一列

**Comment by xiaocheng555** [comment]
> 仍然有prop，但是具体是什么不显示在virtual-column那一列

什么意思，不看懂

**Comment by cug-zgj** [comment]
<img width="1101" alt="image" src="https://github.com/xiaocheng555/el-table-virtual-scroll/assets/20136274/f7f316b1-6dd0-440c-a87c-3c0e59f29d86">
如何让这个名字不显示，现在这个名字是virtual-column的prop

**Comment by cug-zgj** [comment]
没问题了，用slot显示成空了

**Comment by xiaocheng555** [comment]
> 没问题了，用slot显示成空了

ok
