### ISSUE TITLE
使用 <virtual-column> vfixed, 表尾合计行对应的列没有固定

### ISSUE THREAD

**Issue by xieqx1991** [xiaocheng555/el-table-virtual-scroll#89]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/8676463/3f110c68-3851-4a00-bb21-dbb0cd21b1d9)

![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/8676463/5d98c50b-09e6-4c41-8469-fda90ffaa737)

**Comment by xieqx1991** [comment]
![image](https://github.com/xiaocheng555/el-table-virtual-scroll/assets/8676463/b44f8537-d069-4855-8274-425dd4b7e47f)

**Comment by xiaocheng555** [comment]
> ![image](https://private-user-images.githubusercontent.com/8676463/347238365-3f110c68-3851-4a00-bb21-dbb0cd21b1d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODc2ODQsIm5iZiI6MTcyMDU4NzM4NCwicGF0aCI6Ii84Njc2NDYzLzM0NzIzODM2NS0zZjExMGM2OC0zODUxLTRhMDAtYmIyMS1kYmIwY2QyMWIxZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDQ1NjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA4MmJhNzYzZWIzMzBlNzA3NzE4ZTE3NmMwYzExMTQ2NThlN2RlYmZjMGYxOTA0NTAyMzgyMTAzOTMxMzhiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.juvbbNrmCVuPsIwjX_Mg86NqI9XyJud9V5RgimqJqO8)
> 
> ![image](https://private-user-images.githubusercontent.com/8676463/347238441-5d98c50b-09e6-4c41-8469-fda90ffaa737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODc2ODQsIm5iZiI6MTcyMDU4NzM4NCwicGF0aCI6Ii84Njc2NDYzLzM0NzIzODQ0MS01ZDk4YzUwYi0wOWU2LTRjNDEtODQ2OS1mZGE5MGZmYWE3MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDQ1NjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQxMzYyODM1Y2E4OTU1NWNjN2E0NzdmNTc5YWMwZmQyMGIwNGExOTgwYjUyMmY4YjRlODYzZTVhNjk1MjJkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.voU1Xv8-q2dfth95VhLYXK48qY17FTAtjs2tg8FURfs)

已修复，升级到 1.4.3

**Comment by xieqx1991** [comment]
牛的，真速度啊
