### ISSUE TITLE
鼠标拖动滚动条时错位

### ISSUE THREAD

**Issue by qishibo** [xiaocheng555/el-table-virtual-scroll#9]
https://xiaocheng555.github.io/el-table-virtual-scroll/#/SortDemo?code=SortDemo&codeTitle=%E6%8E%92%E5%BA%8F
看的是这个demo，发现拖动滚动条时会出现错位现象，逐渐变大的那种，这种正常么

**Comment by qishibo** [comment]
指的是滑块和鼠标之间的错位

**Comment by xiaocheng555** [comment]
> https://xiaocheng555.github.io/el-table-virtual-scroll/#/SortDemo?code=SortDemo&codeTitle=%E6%8E%92%E5%BA%8F 看的是这个demo，发现拖动滚动条时会出现错位现象，逐渐变大的那种，这种正常么

<img width="676" alt="image" src="https://user-images.githubusercontent.com/19643785/212225829-e7084f43-408b-4fcb-a4e6-fac65e4ab0ee.png">
item-size设置了估计行高为62，但是实际行高是71，而滚动容器是由 2000 * 62（行数 * 行高） 撑起滚动内容高度的，而实际上虚拟滚动会更新实际每行的高度也就是71，导致滚动容器滚动内容高度越来越大于 2000 * 62并慢慢地变为 2000 * 71，所以容器每次滚动都会让容器滚动内容高度变大，是的滚动条错位。

只要将item-size 设置为 71就好了
<img width="824" alt="image" src="https://user-images.githubusercontent.com/19643785/212227645-950aee19-76be-4362-bf74-21bca58d87db.png">

**Comment by xiaocheng555** [comment]
demo 已经更新，如果页面有缓存记得清一下缓存再看效果，排序源码这里是设置为item-size为71的
<img width="947" alt="image" src="https://user-images.githubusercontent.com/19643785/212227838-96bbf08b-7dc2-4c90-8c50-307d7e264333.png">

**Comment by qishibo** [comment]
赞，好使了
