### ISSUE TITLE
tree数据添加append插槽，高度不计算，覆盖掉append

### ISSUE THREAD

**Issue by weizheng1992** [xiaocheng555/el-table-virtual-scroll#93]
<img width="1770" alt="image" src="https://github.com/user-attachments/assets/b0bfc1b0-8e79-4dac-8999-95f3fd10f3c1">
展开后
<img width="1779" alt="image" src="https://github.com/user-attachments/assets/84a4b154-614f-4151-a0be-d3c19a0a38ef">

**Comment by xiaocheng555** [comment]
> <img alt="image" width="1770" src="https://private-user-images.githubusercontent.com/10727313/353409140-b0bfc1b0-8e79-4dac-8999-95f3fd10f3c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMzMyNjEsIm5iZiI6MTcyMjMzMjk2MSwicGF0aCI6Ii8xMDcyNzMxMy8zNTM0MDkxNDAtYjBiZmMxYjAtOGU3OS00ZGFjLTg5OTktOTVmM2ZkMTBmM2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA5NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZWU3NzUyMzNkNDIxOTE0NDI5Yzc0YmNiZmM0ZWNjMmM3ZDBlMTEzN2I1MmU4MTBlNWJiYTNmZWU3NWVlYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6v-aB_hMggBcvxuTUPSI2-7vgVrF4YEuHUVsvYcYUPo"> 展开后 <img alt="image" width="1779" src="https://private-user-images.githubusercontent.com/10727313/353409304-84a4b154-614f-4151-a0be-d3c19a0a38ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMzMyNjEsIm5iZiI6MTcyMjMzMjk2MSwicGF0aCI6Ii8xMDcyNzMxMy8zNTM0MDkzMDQtODRhNGIxNTQtNjE0Zi00MTUxLWEwYmUtZDNjMTlhMGEzOGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA5NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZWVhNzkzNTcxYjYxY2Y3NGI5MWRjMmJhNmU0ZWQyNTk2M2QxNzYwZTdjYWQ5NDRiMjhmZjlhMzZiNDFhOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EUuAyCW8xyiBzzhP6Otj0dk-oLFg8Ud3-pSVFpraTwg">

方便写个demo，我这里复现不出来

**Comment by weizheng1992** [comment]
`<template>
  <div>
    <virtual-scroll
      ref="virtualScroll"
      :data="list"
      :item-size="62"
      key-prop="id"
      @change="virtualList => (tableData = virtualList)">
      <el-table
        v-loading="loading"
        :data="tableData"
        height="500px"
        style="width: 100%"
        border
        row-key="id">
        <el-table-column label="id" prop="id" class-name="el-table__row--level">
          <template slot-scope="{row}">
            <span class="el-table__indent" :style="{ paddingLeft: `${row.level * 16}px` }"></span>
            <div
              v-if="row.hasChildren"
              class="el-table__expand-icon"
              :class="row.expanded ? 'el-table__expand-icon--expanded' : ''"
              @click="onExpand(row)">
              <i class="el-icon-loading" v-if="row.loading"></i>
              <i class="el-icon-arrow-right" v-else></i>
            </div>
            <span v-else class="el-table__placeholder"></span>
            {{row.id}}
          </template>
        </el-table-column>
        <el-table-column label="内容" prop="name"></el-table-column>
        <el-table-column label="内容省略" prop="address" show-overflow-tooltip></el-table-column>

        <div slot="append" class="test">测试测试</div>
      </el-table>
    </virtual-scroll>
  </div>
</template>

<script>
import VirtualScroll from 'el-table-virtual-scroll'

export default {
  components: {
    VirtualScroll
  },
  data () {
    return {
      loading: false,
      list: [],
      tableData: [],
      count: 3000
    }
  },
  methods: {
    fetchData () {
      this.loading = true
      this.list = []
      setTimeout(() => {
        this.list =  [{
          id: 1,
          date: '2016-05-02',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          id: 2,
          date: '2016-05-04',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1517 弄'
        }, {
          id: 3,
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1519 弄',
          children: [{
              id: 31,
              date: '2016-05-01',
              name: '王小虎',
              address: '上海市普陀区金沙江路 1519 弄'
            }, {
              id: 32,
              date: '2016-05-01',
              name: '王小虎',
              address: '上海市普陀区金沙江路 1519 弄'
          }]
        }, {
          id: 4,
          date: '2016-05-03',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1516 弄'
        }],
        this.loading = false
      }, 1000)
    },
    getRandomContent () {
      const content = [
        '这是一条测试数据',
        '君不见黄河之水天上来，奔流到海不复回。',
        '十年生死两茫茫',
        '寻寻觅觅，冷冷清清，凄凄惨惨戚戚。',
        '桃花坞里桃花庵，桃花庵里桃花仙；桃花仙人种桃树，又摘桃花卖酒钱。',
        '明月几时有，把酒问青天。',
        '槛菊愁烟兰泣露，罗幕轻寒，',
        '寒蝉凄切，对长亭晚，骤雨初歇。都门帐饮无绪，留恋处，兰舟催发。执手相看泪眼，竟无语凝噎。念去去，千里烟波，暮霭沉沉楚天阔。多情自古伤离别，更那堪冷落清秋节！今宵酒醒何处？杨柳岸，晓风残月。此去经年，应是良辰好景虚设。便纵有千种风情，更与何人说？',
        '红豆生南国，春来发几枝。',
        '黄鹂'
      ]
      const i = Math.floor(Math.random() * 10)
      return content[i]
    },
    // 展开收起事件
    onExpand (row) {
      row.expanded = !row.expanded
      // if (row.expanded) {
      //   this.loadChildNodes(row)
      // } else {
      //   this.hideChildNodes(row)
      // }
    },
    // 加载子节点
    loadChildNodes (row) {
      // 如果已经加载，则显示隐藏的字节点
      if (row.loaded) {
        const index = this.list.findIndex(item => item === row)
        if (index > -1) {
          this.list.splice(index + 1, 0, ...row.hideNodes)
        }
        return
      }

      // 获取子节点数据并显示
      row.loading = true
      setTimeout(() => {
        row.loading = false
        row.loaded = true

        const data = []
        for (let i = 0; i < 10; i++) {
          data.push({
            id: this.count++,
            show: false,
            text: this.getRandomContent(),
            text2: this.getRandomContent(),
            hasChildren: row.level > 3 ? false : true,
            expanded: false,
            loading: false,
            level: row.level + 1,
            hideNodes: []
          })
        }

        // 所有子节点插入到当前同级节点下
        const index = this.list.findIndex(item => item === row)
        if (index > -1) {
          this.list.splice(index + 1, 0, ...data)
        }
      }, 1000)
    },
    // 隐藏子节点
    hideChildNodes (row) {
      const index = this.list.findIndex(item => item === row)
      if (index === -1) return

      // 查找当前节点的所有子孙节点
      const hideNodes = []
      for (let i = index + 1; i < this.list.length; i++) {
        const curRow = this.list[i]
        if (curRow.level <= row.level) break
        hideNodes.push(curRow)
      }
      row.hideNodes = hideNodes
      // 隐藏所有子孙节点
      this.list = this.list.filter(item => !hideNodes.includes(item))
    }
  },
  created () {
    this.fetchData()
  }
}
</script>

<style lang='less' scoped>
.test{
  height: 200px;
}
</style>
`

**Comment by weizheng1992** [comment]
<template>
  <div>
    <virtual-scroll
      ref="virtualScroll"
      :data="list"
      :item-size="62"
      key-prop="id"
      @change="virtualList => (tableData = virtualList)">
      <el-table
        v-loading="loading"
        :data="tableData"
        height="500px"
        style="width: 100%"
        border
        row-key="id">
        <el-table-column label="id" prop="id" class-name="el-table__row--level">
          <template slot-scope="{row}">
            <span class="el-table__indent" :style="{ paddingLeft: `${row.level * 16}px` }"></span>
            <div
              v-if="row.hasChildren"
              class="el-table__expand-icon"
              :class="row.expanded ? 'el-table__expand-icon--expanded' : ''"
              @click="onExpand(row)">
              <i class="el-icon-loading" v-if="row.loading"></i>
              <i class="el-icon-arrow-right" v-else></i>
            </div>
            <span v-else class="el-table__placeholder"></span>
            {{row.id}}
          </template>
        </el-table-column>
        <el-table-column label="内容" prop="name"></el-table-column>
        <el-table-column label="内容省略" prop="address" show-overflow-tooltip></el-table-column>

        <div slot="append" class="test">测试测试</div>
      </el-table>
    </virtual-scroll>
  </div>
</template>

<script>
import VirtualScroll from 'el-table-virtual-scroll'

export default {
  components: {
    VirtualScroll
  },
  data () {
    return {
      loading: false,
      list: [],
      tableData: [],
      count: 3000
    }
  },
  methods: {
    fetchData () {
      this.loading = true
      this.list = []
      setTimeout(() => {
        this.list =  [{
          id: 1,
          date: '2016-05-02',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          id: 2,
          date: '2016-05-04',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1517 弄'
        }, {
          id: 3,
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1519 弄',
          children: [{
              id: 31,
              date: '2016-05-01',
              name: '王小虎',
              address: '上海市普陀区金沙江路 1519 弄'
            }, {
              id: 32,
              date: '2016-05-01',
              name: '王小虎',
              address: '上海市普陀区金沙江路 1519 弄'
          }]
        }, {
          id: 4,
          date: '2016-05-03',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1516 弄'
        }],
        this.loading = false
      }, 1000)
    },
    getRandomContent () {
      const content = [
        '这是一条测试数据',
        '君不见黄河之水天上来，奔流到海不复回。',
        '十年生死两茫茫',
        '寻寻觅觅，冷冷清清，凄凄惨惨戚戚。',
        '桃花坞里桃花庵，桃花庵里桃花仙；桃花仙人种桃树，又摘桃花卖酒钱。',
        '明月几时有，把酒问青天。',
        '槛菊愁烟兰泣露，罗幕轻寒，',
        '寒蝉凄切，对长亭晚，骤雨初歇。都门帐饮无绪，留恋处，兰舟催发。执手相看泪眼，竟无语凝噎。念去去，千里烟波，暮霭沉沉楚天阔。多情自古伤离别，更那堪冷落清秋节！今宵酒醒何处？杨柳岸，晓风残月。此去经年，应是良辰好景虚设。便纵有千种风情，更与何人说？',
        '红豆生南国，春来发几枝。',
        '黄鹂'
      ]
      const i = Math.floor(Math.random() * 10)
      return content[i]
    },
    // 展开收起事件
    onExpand (row) {
      row.expanded = !row.expanded
      // if (row.expanded) {
      //   this.loadChildNodes(row)
      // } else {
      //   this.hideChildNodes(row)
      // }
    },
    // 加载子节点
    loadChildNodes (row) {
      // 如果已经加载，则显示隐藏的字节点
      if (row.loaded) {
        const index = this.list.findIndex(item => item === row)
        if (index > -1) {
          this.list.splice(index + 1, 0, ...row.hideNodes)
        }
        return
      }

      // 获取子节点数据并显示
      row.loading = true
      setTimeout(() => {
        row.loading = false
        row.loaded = true

        const data = []
        for (let i = 0; i < 10; i++) {
          data.push({
            id: this.count++,
            show: false,
            text: this.getRandomContent(),
            text2: this.getRandomContent(),
            hasChildren: row.level > 3 ? false : true,
            expanded: false,
            loading: false,
            level: row.level + 1,
            hideNodes: []
          })
        }

        // 所有子节点插入到当前同级节点下
        const index = this.list.findIndex(item => item === row)
        if (index > -1) {
          this.list.splice(index + 1, 0, ...data)
        }
      }, 1000)
    },
    // 隐藏子节点
    hideChildNodes (row) {
      const index = this.list.findIndex(item => item === row)
      if (index === -1) return

      // 查找当前节点的所有子孙节点
      const hideNodes = []
      for (let i = index + 1; i < this.list.length; i++) {
        const curRow = this.list[i]
        if (curRow.level <= row.level) break
        hideNodes.push(curRow)
      }
      row.hideNodes = hideNodes
      // 隐藏所有子孙节点
      this.list = this.list.filter(item => !hideNodes.includes(item))
    }
  },
  created () {
    this.fetchData()
  }
}
</script>

<style lang='less' scoped>
.test{
  height: 200px;
}
</style>

**Comment by weizheng1992** [comment]
```
<template>
  <div>
    <virtual-scroll
      ref="virtualScroll"
      :data="list"
      :item-size="62"
      key-prop="id"
      @change="virtualList => (tableData = virtualList)">
      <el-table
        v-loading="loading"
        :data="tableData"
        height="500px"
        style="width: 100%"
        border
        row-key="id">
        <el-table-column label="id" prop="id" class-name="el-table__row--level">
          <template slot-scope="{row}">
            <span class="el-table__indent" :style="{ paddingLeft: `${row.level * 16}px` }"></span>
            <div
              v-if="row.hasChildren"
              class="el-table__expand-icon"
              :class="row.expanded ? 'el-table__expand-icon--expanded' : ''"
              @click="onExpand(row)">
              <i class="el-icon-loading" v-if="row.loading"></i>
              <i class="el-icon-arrow-right" v-else></i>
            </div>
            <span v-else class="el-table__placeholder"></span>
            {{row.id}}
          </template>
        </el-table-column>
        <el-table-column label="内容" prop="name"></el-table-column>
        <el-table-column label="内容省略" prop="address" show-overflow-tooltip></el-table-column>

        <div slot="append" class="test">测试测试</div>
      </el-table>
    </virtual-scroll>
  </div>
</template>

<script>
import VirtualScroll from 'el-table-virtual-scroll'

export default {
  components: {
    VirtualScroll
  },
  data () {
    return {
      loading: false,
      list: [],
      tableData: [],
      count: 3000
    }
  },
  methods: {
    fetchData () {
      this.loading = true
      this.list = []
      setTimeout(() => {
        this.list =  [{
          id: 1,
          date: '2016-05-02',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          id: 2,
          date: '2016-05-04',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1517 弄'
        }, {
          id: 3,
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1519 弄',
          children: [{
              id: 31,
              date: '2016-05-01',
              name: '王小虎',
              address: '上海市普陀区金沙江路 1519 弄'
            }, {
              id: 32,
              date: '2016-05-01',
              name: '王小虎',
              address: '上海市普陀区金沙江路 1519 弄'
          }]
        }, {
          id: 4,
          date: '2016-05-03',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1516 弄'
        }],
        this.loading = false
      }, 1000)
    },
    getRandomContent () {
      const content = [
        '这是一条测试数据',
        '君不见黄河之水天上来，奔流到海不复回。',
        '十年生死两茫茫',
        '寻寻觅觅，冷冷清清，凄凄惨惨戚戚。',
        '桃花坞里桃花庵，桃花庵里桃花仙；桃花仙人种桃树，又摘桃花卖酒钱。',
        '明月几时有，把酒问青天。',
        '槛菊愁烟兰泣露，罗幕轻寒，',
        '寒蝉凄切，对长亭晚，骤雨初歇。都门帐饮无绪，留恋处，兰舟催发。执手相看泪眼，竟无语凝噎。念去去，千里烟波，暮霭沉沉楚天阔。多情自古伤离别，更那堪冷落清秋节！今宵酒醒何处？杨柳岸，晓风残月。此去经年，应是良辰好景虚设。便纵有千种风情，更与何人说？',
        '红豆生南国，春来发几枝。',
        '黄鹂'
      ]
      const i = Math.floor(Math.random() * 10)
      return content[i]
    },
    // 展开收起事件
    onExpand (row) {
      row.expanded = !row.expanded
      // if (row.expanded) {
      //   this.loadChildNodes(row)
      // } else {
      //   this.hideChildNodes(row)
      // }
    },
    // 加载子节点
    loadChildNodes (row) {
      // 如果已经加载，则显示隐藏的字节点
      if (row.loaded) {
        const index = this.list.findIndex(item => item === row)
        if (index > -1) {
          this.list.splice(index + 1, 0, ...row.hideNodes)
        }
        return
      }

      // 获取子节点数据并显示
      row.loading = true
      setTimeout(() => {
        row.loading = false
        row.loaded = true

        const data = []
        for (let i = 0; i < 10; i++) {
          data.push({
            id: this.count++,
            show: false,
            text: this.getRandomContent(),
            text2: this.getRandomContent(),
            hasChildren: row.level > 3 ? false : true,
            expanded: false,
            loading: false,
            level: row.level + 1,
            hideNodes: []
          })
        }

        // 所有子节点插入到当前同级节点下
        const index = this.list.findIndex(item => item === row)
        if (index > -1) {
          this.list.splice(index + 1, 0, ...data)
        }
      }, 1000)
    },
    // 隐藏子节点
    hideChildNodes (row) {
      const index = this.list.findIndex(item => item === row)
      if (index === -1) return

      // 查找当前节点的所有子孙节点
      const hideNodes = []
      for (let i = index + 1; i < this.list.length; i++) {
        const curRow = this.list[i]
        if (curRow.level <= row.level) break
        hideNodes.push(curRow)
      }
      row.hideNodes = hideNodes
      // 隐藏所有子孙节点
      this.list = this.list.filter(item => !hideNodes.includes(item))
    }
  },
  created () {
    this.fetchData()
  }
}
</script>

<style lang='less' scoped>
.test{
  height: 200px;
}
</style>

```

**Comment by weizheng1992** [comment]
数据返回了children ，直接展开是不可以的

**Comment by weizheng1992** [comment]
el-table 加上  :default-expand-all="true" 在滚动，之前折叠的数据，会展开

**Comment by xiaocheng555** [comment]
> el-table 加上 :default-expand-all="true" 在滚动，之前折叠的数据，会展开

组件不支持children这种树结构

**Comment by xiaocheng555** [comment]
<img width="441" alt="image" src="https://github.com/user-attachments/assets/e3f88b08-39e1-4cea-a79c-8155cc48ee96">
参考这两个demo

**Comment by weizheng1992** [comment]
哦，那不符合需求了，算了
