### ISSUE TITLE
tree状态下无法一次性展开全部

### ISSUE THREAD

**Issue by gongxiansheng** [xiaocheng555/el-table-virtual-scroll#94]
tree状态下无法一次性展开全部，这个要修复吗

**Comment by xiaocheng555** [comment]
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/c8c8d18d-c790-4872-99a2-4bafd126257e">
这里支持展开全部，不过是展开已经加载过的树数据

**Comment by gongxiansheng** [comment]
[官方demo都不行呢？](https://xiaocheng555.github.io/el-table-virtual-scroll/#/VTreeDemo2?code=VTreeDemo2&codeTitle=%E6%A8%A1%E6%8B%9F%E6%A0%91%E7%BB%93%E6%9E%84%E6%87%92%E5%8A%A0%E8%BD%BD2)

**Comment by xiaocheng555** [comment]
> [官方demo都不行呢？](https://xiaocheng555.github.io/el-table-virtual-scroll/#/VTreeDemo2?code=VTreeDemo2&codeTitle=%E6%A8%A1%E6%8B%9F%E6%A0%91%E7%BB%93%E6%9E%84%E6%87%92%E5%8A%A0%E8%BD%BD2)

要先手动展开

**Comment by gongxiansheng** [comment]
`非懒加载的树结构需要写成懒加载的形式，否则树展开后，来回滚动会导致展开树重置为未展开状态`，先手动展开，expandAll也没有实现一次性展开

**Comment by xiaocheng555** [comment]
![image](https://github.com/user-attachments/assets/43c7f179-819e-4f62-8e4a-b250891b3848)
yong用这种方式试试
