### ISSUE TITLE
请问用了模拟树结构懒加载后 排序功能要怎么写呀?

### ISSUE THREAD

**Issue by Nxir** [xiaocheng555/el-table-virtual-scroll#96]
现在点排序 数据都是乱的

**Comment by xiaocheng555** [comment]
> 现在点排序 数据都是乱的

是bug，没有兼容这种情况，晚点我兼容下

**Comment by xiaocheng555** [comment]
> > 现在点排序 数据都是乱的
> 
> 是bug，没有兼容这种情况，晚点我兼容下

树结构排序和筛选没有兼容方法，现在不支持

**Comment by xiaocheng555** [comment]
https://xiaocheng555.github.io/el-table-virtual-scroll/#/VTreeDemo?code=VTreeDemo&codeTitle=%E6%A0%91%E5%BD%A2%E8%A1%A8%E6%A0%BC-%E6%87%92%E5%8A%A0%E8%BD%BD

2.0.0 版本支持

**Comment by Nxir** [comment]
大佬牛批   刚看到  这段时间我已经自己实现排序了  

通过table的@sort-change方法修改dataList  
virtual-column的:sortable需要设置为'custom'

**Comment by Nxir** [comment]
> https://xiaocheng555.github.io/el-table-virtual-scroll/#/VTreeDemo?code=VTreeDemo&codeTitle=%E6%A0%91%E5%BD%A2%E8%A1%A8%E6%A0%BC-%E6%87%92%E5%8A%A0%E8%BD%BD
> 
> 2.0.0 版本支持

牛批  刚看到...  这段时间我已经实现了  
通过table的@sort-change方法修改dataList  
column的:sortable设为"custom"
