### ISSUE TITLE
请问用了模拟树结构后，还能使用多选么

### ISSUE THREAD

**Issue by cug-zgj** [xiaocheng555/el-table-virtual-scroll#97]

**Comment by xiaocheng555** [comment]
能的

**Comment by cug-zgj** [comment]
是使用两个virtual-column么



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月22日(星期四) 下午2:38
收件人: ***@***.***&gt;; 
抄送: "Unlimited Blade ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaocheng555/el-table-virtual-scroll] 请问用了模拟树结构后，还能使用多选么 (Issue #97)














 
能的

**Comment by cug-zgj** [comment]
是使用两个virtual-column么

**Comment by xiaocheng555** [comment]
对

**Comment by cug-zgj** [comment]
好的，我试试
